"""Closed B-05 measurement authoring vocabularies."""

from __future__ import annotations

from enum import Enum
from types import MappingProxyType


class MeasurementRole(str, Enum):
    MANDATORY = "MANDATORY"
    SOFT = "SOFT"
    DIAGNOSTIC = "DIAGNOSTIC"


class ScientificValueState(str, Enum):
    BOUND = "BOUND"
    HUMAN_INPUT = "HUMAN_INPUT"
    BLOCKED_FOR_LIVE_UNTIL_SET = "BLOCKED_FOR_LIVE_UNTIL_SET"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class StratumApplicabilityStatus(str, Enum):
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    HUMAN_INPUT = "HUMAN_INPUT"


class DependenceShortcutKind(str, Enum):
    QUADRATURE = "QUADRATURE"
    INDEPENDENCE = "INDEPENDENCE"
    ZERO_COVARIANCE = "ZERO_COVARIANCE"


class ReconstructionEvidenceStage(str, Enum):
    BASE_REQUIRED = "BASE_REQUIRED"
    BASE_COMPLETE = "BASE_COMPLETE"
    NOMINATED = "NOMINATED"
    EXTENDED = "EXTENDED"
    PROMOTION_ELIGIBLE = "PROMOTION_ELIGIBLE"


class ReconstructionEvidenceOutcome(str, Enum):
    STAGE_ESTABLISHED = "STAGE_ESTABLISHED"
    EVIDENCE_DEFERRED = "EVIDENCE_DEFERRED"
    INDETERMINATE_INSUFFICIENT_EVIDENCE = "INDETERMINATE_INSUFFICIENT_EVIDENCE"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    RECONSTRUCTION_FAILURE = "RECONSTRUCTION_FAILURE"


class ReconstructionStopKind(str, Enum):
    NONE = "NONE"
    HEURISTIC_FUTILITY = "HEURISTIC_FUTILITY"
    SCIENTIFIC_EVIDENCE_EXHAUSTED = "SCIENTIFIC_EVIDENCE_EXHAUSTED"
    RECONSTRUCTION_EXECUTION_FAILURE = "RECONSTRUCTION_EXECUTION_FAILURE"


class MeasurementEvidenceRole(str, Enum):
    ANALYTIC_OR_MANUFACTURED_VERIFICATION = "ANALYTIC_OR_MANUFACTURED_VERIFICATION"
    REFINEMENT_OR_CONVERGENCE = "REFINEMENT_OR_CONVERGENCE"
    INDEPENDENT_WITNESS = "INDEPENDENT_WITNESS"
    LIMITING_CASE_OR_INVARIANCE = "LIMITING_CASE_OR_INVARIANCE"
    EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION = "EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION"


class MeasurementClaimClass(str, Enum):
    IMPLEMENTATION_CORRECTNESS = "IMPLEMENTATION_CORRECTNESS"
    DISCRETIZATION_CONVERGENCE = "DISCRETIZATION_CONVERGENCE"
    REFERENCE_AGREEMENT = "REFERENCE_AGREEMENT"
    LIMITING_CASE_BEHAVIOR = "LIMITING_CASE_BEHAVIOR"
    PHYSICAL_MODEL_VALIDITY = "PHYSICAL_MODEL_VALIDITY"
    TARGET_WORKLOAD_APPLICABILITY = "TARGET_WORKLOAD_APPLICABILITY"
    ENGINEERING_CONTEXT_OF_USE = "ENGINEERING_CONTEXT_OF_USE"
    MEASUREMENT_UNCERTAINTY_ADEQUACY = "MEASUREMENT_UNCERTAINTY_ADEQUACY"


class MeasurementDefinitionKind(str, Enum):
    SCIENTIFIC_PROPERTY = "SCIENTIFIC_PROPERTY"
    OBSERVABLE = "OBSERVABLE"
    COORDINATE_SYSTEM = "COORDINATE_SYSTEM"
    UNIT = "UNIT"
    NUMERICAL_OPERATOR = "NUMERICAL_OPERATOR"
    DISCRETIZATION = "DISCRETIZATION"
    SAMPLING_QUADRATURE = "SAMPLING_QUADRATURE"
    NORMALIZATION = "NORMALIZATION"
    AGGREGATION = "AGGREGATION"
    PRECISION = "PRECISION"
    SCIENTIFIC_VALUE = "SCIENTIFIC_VALUE"
    APPLICABILITY_POLICY = "APPLICABILITY_POLICY"
    APPLICABILITY_EVIDENCE = "APPLICABILITY_EVIDENCE"
    APPLICABILITY_REASON = "APPLICABILITY_REASON"
    STRATUM = "STRATUM"
    KNOWN_LIMITATION = "KNOWN_LIMITATION"
    IMPLEMENTATION = "IMPLEMENTATION"
    EVIDENCE_SOURCE = "EVIDENCE_SOURCE"
    CASE_SCOPE = "CASE_SCOPE"
    ESTIMAND = "ESTIMAND"
    MEASUREMENT_OUTPUT = "MEASUREMENT_OUTPUT"
    SAMPLING_UNIT = "SAMPLING_UNIT"
    RESAMPLING_UNIT = "RESAMPLING_UNIT"
    INDEPENDENCE_UNIT = "INDEPENDENCE_UNIT"
    COMMON_CASE_PAIRING = "COMMON_CASE_PAIRING"
    RECONSTRUCTION_CASE_INTERACTION = "RECONSTRUCTION_CASE_INTERACTION"
    RECONSTRUCTION_STRATUM_INTERACTION = "RECONSTRUCTION_STRATUM_INTERACTION"
    JOINT_REFERENCE_UNCERTAINTY = "JOINT_REFERENCE_UNCERTAINTY"
    REFERENCE_CANDIDATE_COVARIANCE = "REFERENCE_CANDIDATE_COVARIANCE"
    REPRESENTATION_DEPENDENCE = "REPRESENTATION_DEPENDENCE"
    EXECUTION_DEPENDENCE = "EXECUTION_DEPENDENCE"
    CENSORING_ACCOUNTING = "CENSORING_ACCOUNTING"
    EVIDENCE_MINIMUM = "EVIDENCE_MINIMUM"
    STRATUM_EVIDENCE_MINIMUM = "STRATUM_EVIDENCE_MINIMUM"
    STOPPING_RULE = "STOPPING_RULE"
    EVIDENCE_EXTENSION_RULE = "EVIDENCE_EXTENSION_RULE"
    INTERVAL_ERROR_CONTROL = "INTERVAL_ERROR_CONTROL"
    MULTIPLICITY_POLICY = "MULTIPLICITY_POLICY"
    EVIDENCE_SET = "EVIDENCE_SET"
    DEPENDENCE_ASSUMPTION = "DEPENDENCE_ASSUMPTION"
    APPLICABILITY_TEST = "APPLICABILITY_TEST"
    DOSSIER_QUALIFICATION = "DOSSIER_QUALIFICATION"
    CONSTRUCTION_FAMILY = "CONSTRUCTION_FAMILY"
    COMPLETE_BASE_MINIMUM = "COMPLETE_BASE_MINIMUM"
    BUILD_COMPLETENESS_CRITERIA = "BUILD_COMPLETENESS_CRITERIA"
    FROZEN_ARTIFACT_REUSE_POLICY = "FROZEN_ARTIFACT_REUSE_POLICY"
    NOMINATION_CRITERIA = "NOMINATION_CRITERIA"
    PROMOTION_CRITERIA = "PROMOTION_CRITERIA"
    CASE_COVERAGE_REQUIREMENT = "CASE_COVERAGE_REQUIREMENT"
    STRATUM_COVERAGE_REQUIREMENT = "STRATUM_COVERAGE_REQUIREMENT"
    STABILITY_AUDIT_RATE = "STABILITY_AUDIT_RATE"
    AUDIT_SELECTION_POLICY = "AUDIT_SELECTION_POLICY"
    POWER_REQUIREMENT = "POWER_REQUIREMENT"
    MINIMUM_RESOLVABLE_IMPROVEMENT = "MINIMUM_RESOLVABLE_IMPROVEMENT"
    SEQUENTIAL_STOPPING_RULE = "SEQUENTIAL_STOPPING_RULE"
    COMPLETE_BASE_EVIDENCE = "COMPLETE_BASE_EVIDENCE"
    NOMINATION_EVIDENCE = "NOMINATION_EVIDENCE"
    EXTENSION_EVIDENCE = "EXTENSION_EVIDENCE"
    PROMOTION_EVIDENCE = "PROMOTION_EVIDENCE"
    REMAINING_EVIDENCE_REQUIREMENT = "REMAINING_EVIDENCE_REQUIREMENT"
    RECONSTRUCTION_EXECUTION_FAILURE = "RECONSTRUCTION_EXECUTION_FAILURE"


_I = MeasurementClaimClass.IMPLEMENTATION_CORRECTNESS
_C = MeasurementClaimClass.DISCRETIZATION_CONVERGENCE
_R = MeasurementClaimClass.REFERENCE_AGREEMENT
_L = MeasurementClaimClass.LIMITING_CASE_BEHAVIOR
_P = MeasurementClaimClass.PHYSICAL_MODEL_VALIDITY
_W = MeasurementClaimClass.TARGET_WORKLOAD_APPLICABILITY
_E = MeasurementClaimClass.ENGINEERING_CONTEXT_OF_USE
_U = MeasurementClaimClass.MEASUREMENT_UNCERTAINTY_ADEQUACY

MEASUREMENT_EVIDENCE_ROLE_CLAIMS = MappingProxyType(
    {
        MeasurementEvidenceRole.ANALYTIC_OR_MANUFACTURED_VERIFICATION: frozenset(
            {_I, _R, _L}
        ),
        MeasurementEvidenceRole.REFINEMENT_OR_CONVERGENCE: frozenset({_I, _C, _L, _U}),
        MeasurementEvidenceRole.INDEPENDENT_WITNESS: frozenset({_I, _C, _R, _L, _U}),
        MeasurementEvidenceRole.LIMITING_CASE_OR_INVARIANCE: frozenset({_I, _L}),
        MeasurementEvidenceRole.EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION: frozenset(
            {_R, _L, _P, _W, _E, _U}
        ),
    }
)


__all__ = (
    "MEASUREMENT_EVIDENCE_ROLE_CLAIMS",
    "DependenceShortcutKind",
    "MeasurementClaimClass",
    "MeasurementDefinitionKind",
    "MeasurementEvidenceRole",
    "MeasurementRole",
    "ReconstructionEvidenceOutcome",
    "ReconstructionEvidenceStage",
    "ReconstructionStopKind",
    "ScientificValueState",
    "StratumApplicabilityStatus",
)
