"""Closed B-05 measurement authoring vocabularies."""

from __future__ import annotations

from enum import Enum
from types import MappingProxyType


class MeasurementRole(str, Enum):
    MANDATORY = "MANDATORY"
    SOFT = "SOFT"
    DIAGNOSTIC = "DIAGNOSTIC"


class ScientificValueState(str, Enum):
    BOUND = "BOUND"
    HUMAN_INPUT = "HUMAN_INPUT"
    BLOCKED_FOR_LIVE_UNTIL_SET = "BLOCKED_FOR_LIVE_UNTIL_SET"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class StratumApplicabilityStatus(str, Enum):
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    HUMAN_INPUT = "HUMAN_INPUT"


class MeasurementEvidenceRole(str, Enum):
    ANALYTIC_OR_MANUFACTURED_VERIFICATION = "ANALYTIC_OR_MANUFACTURED_VERIFICATION"
    REFINEMENT_OR_CONVERGENCE = "REFINEMENT_OR_CONVERGENCE"
    INDEPENDENT_WITNESS = "INDEPENDENT_WITNESS"
    LIMITING_CASE_OR_INVARIANCE = "LIMITING_CASE_OR_INVARIANCE"
    EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION = "EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION"


class MeasurementClaimClass(str, Enum):
    IMPLEMENTATION_CORRECTNESS = "IMPLEMENTATION_CORRECTNESS"
    DISCRETIZATION_CONVERGENCE = "DISCRETIZATION_CONVERGENCE"
    REFERENCE_AGREEMENT = "REFERENCE_AGREEMENT"
    LIMITING_CASE_BEHAVIOR = "LIMITING_CASE_BEHAVIOR"
    PHYSICAL_MODEL_VALIDITY = "PHYSICAL_MODEL_VALIDITY"
    TARGET_WORKLOAD_APPLICABILITY = "TARGET_WORKLOAD_APPLICABILITY"
    ENGINEERING_CONTEXT_OF_USE = "ENGINEERING_CONTEXT_OF_USE"
    MEASUREMENT_UNCERTAINTY_ADEQUACY = "MEASUREMENT_UNCERTAINTY_ADEQUACY"


class MeasurementDefinitionKind(str, Enum):
    SCIENTIFIC_PROPERTY = "SCIENTIFIC_PROPERTY"
    OBSERVABLE = "OBSERVABLE"
    COORDINATE_SYSTEM = "COORDINATE_SYSTEM"
    UNIT = "UNIT"
    NUMERICAL_OPERATOR = "NUMERICAL_OPERATOR"
    DISCRETIZATION = "DISCRETIZATION"
    SAMPLING_QUADRATURE = "SAMPLING_QUADRATURE"
    NORMALIZATION = "NORMALIZATION"
    AGGREGATION = "AGGREGATION"
    PRECISION = "PRECISION"
    SCIENTIFIC_VALUE = "SCIENTIFIC_VALUE"
    APPLICABILITY_POLICY = "APPLICABILITY_POLICY"
    APPLICABILITY_EVIDENCE = "APPLICABILITY_EVIDENCE"
    APPLICABILITY_REASON = "APPLICABILITY_REASON"
    STRATUM = "STRATUM"
    KNOWN_LIMITATION = "KNOWN_LIMITATION"
    IMPLEMENTATION = "IMPLEMENTATION"
    EVIDENCE_SOURCE = "EVIDENCE_SOURCE"
    CASE_SCOPE = "CASE_SCOPE"


_I = MeasurementClaimClass.IMPLEMENTATION_CORRECTNESS
_C = MeasurementClaimClass.DISCRETIZATION_CONVERGENCE
_R = MeasurementClaimClass.REFERENCE_AGREEMENT
_L = MeasurementClaimClass.LIMITING_CASE_BEHAVIOR
_P = MeasurementClaimClass.PHYSICAL_MODEL_VALIDITY
_W = MeasurementClaimClass.TARGET_WORKLOAD_APPLICABILITY
_E = MeasurementClaimClass.ENGINEERING_CONTEXT_OF_USE
_U = MeasurementClaimClass.MEASUREMENT_UNCERTAINTY_ADEQUACY

MEASUREMENT_EVIDENCE_ROLE_CLAIMS = MappingProxyType(
    {
        MeasurementEvidenceRole.ANALYTIC_OR_MANUFACTURED_VERIFICATION: frozenset(
            {_I, _R, _L}
        ),
        MeasurementEvidenceRole.REFINEMENT_OR_CONVERGENCE: frozenset({_I, _C, _L, _U}),
        MeasurementEvidenceRole.INDEPENDENT_WITNESS: frozenset({_I, _C, _R, _L, _U}),
        MeasurementEvidenceRole.LIMITING_CASE_OR_INVARIANCE: frozenset({_I, _L}),
        MeasurementEvidenceRole.EXPERIMENTAL_OR_INDUSTRIAL_VALIDATION: frozenset(
            {_R, _L, _P, _W, _E, _U}
        ),
    }
)


__all__ = (
    "MEASUREMENT_EVIDENCE_ROLE_CLAIMS",
    "MeasurementClaimClass",
    "MeasurementDefinitionKind",
    "MeasurementEvidenceRole",
    "MeasurementRole",
    "ScientificValueState",
    "StratumApplicabilityStatus",
)
