"""Provider-neutral compute types.

Ownership is structural. A :class:`CarbonOwnedResource` can only be issued by
:class:`carbon.compute.store.ComputeStore` from an intent Carbon itself
persisted for a campaign, and it is the only type any terminate path accepts.
A :class:`UserManagedHost` (a miner's own machine or a remote Docker host) is a
different type with no stop or terminate capability at all, and a raw provider
resource id - even a perfectly valid one - is refused because it did not come
through the store.
"""

from __future__ import annotations

import hashlib
import json
import re
import secrets
from dataclasses import asdict, dataclass, field
from enum import StrEnum

__all__ = [
    "OWNERSHIP_NAME_PATTERN",
    "CarbonOwnedResource",
    "IntentState",
    "Offer",
    "PodSpec",
    "ProvisionRequest",
    "ResourceState",
    "UserManagedHost",
    "new_ownership_tag",
    "ownership_name",
]

# A Carbon-created resource is named ``carbon-<24 lowercase hex>``; the nonce is
# generated by Carbon per intent and is the discoverable ownership tag.
OWNERSHIP_NAME_PATTERN = re.compile(r"^carbon-([0-9a-f]{24})$")
_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")


def new_ownership_tag() -> str:
    return secrets.token_hex(12)


def ownership_name(tag: str) -> str:
    name = f"carbon-{tag}"
    if not OWNERSHIP_NAME_PATTERN.fullmatch(name):
        raise ValueError("malformed ownership tag")
    return name


class IntentState(StrEnum):
    """Carbon's knowledge about a provisioning request."""

    REQUESTED = "requested"  # persisted; provider not contacted
    DISPATCHED = "dispatched"  # request may have reached the provider; id unknown
    BOUND = "bound"  # provider resource id recorded
    REJECTED = "rejected"  # provider definitively refused; nothing created
    NOT_FOUND = "not_found"  # dispatched, then no tagged resource found
    CANCELLED = "cancelled"  # cancelled before dispatch


class ResourceState(StrEnum):
    STARTING = "starting"
    PULLING_IMAGE = "pulling_image"
    RUNNING = "running"
    EXPORTING = "exporting"
    STOPPED = "stopped"
    TERMINATING = "terminating"
    TERMINATED = "terminated"
    UNKNOWN = "unknown"


# States in which compute (not just storage) is billed.
COMPUTE_BILLED = frozenset(
    {
        ResourceState.STARTING,
        ResourceState.PULLING_IMAGE,
        ResourceState.RUNNING,
        ResourceState.EXPORTING,
        ResourceState.TERMINATING,
        ResourceState.UNKNOWN,
    }
)
# States in which storage persists and is billed.
STORAGE_BILLED = COMPUTE_BILLED | {ResourceState.STOPPED}


def _checked_id(value: str, what: str) -> str:
    if not isinstance(value, str) or not _ID.fullmatch(value):
        raise ValueError(f"invalid {what}")
    return value


@dataclass(frozen=True)
class PodSpec:
    """What to provision. Rates are caller-supplied observations, never defaults."""

    image: str
    gpu_type_id: str | None
    gpu_count: int = 0
    cloud_type: str = "SECURE"
    container_disk_gb: int = 20
    volume_gb: int = 0
    ports: tuple[str, ...] = ()
    env: tuple[tuple[str, str], ...] = ()
    max_rate_usd_per_hr: float | None = None
    storage_usd_per_gb_month: float | None = None

    def __post_init__(self) -> None:
        if not self.image or "@sha256:" not in self.image:
            raise ValueError("image must be pinned by digest")
        if self.gpu_count < 0 or self.container_disk_gb < 0 or self.volume_gb < 0:
            raise ValueError("negative resource request")
        if (self.gpu_count > 0) != (self.gpu_type_id is not None):
            raise ValueError("gpu_type_id and gpu_count must agree")
        if self.cloud_type not in {"SECURE", "COMMUNITY"}:
            raise ValueError("cloud_type must be SECURE or COMMUNITY")
        for key, _ in self.env:
            if key.startswith("CARBON_OWNERSHIP"):
                raise ValueError("ownership env is Carbon-assigned")

    @property
    def storage_gb(self) -> int:
        return self.container_disk_gb + self.volume_gb

    def canonical(self) -> dict[str, object]:
        value = asdict(self)
        value["ports"] = list(self.ports)
        value["env"] = [list(item) for item in self.env]
        return value


@dataclass(frozen=True)
class ProvisionRequest:
    tenant: str
    miner: str
    campaign_id: str
    intent_id: str
    spec: PodSpec
    deadline_at: float

    def __post_init__(self) -> None:
        _checked_id(self.tenant, "tenant")
        _checked_id(self.miner, "miner")
        _checked_id(self.campaign_id, "campaign_id")
        _checked_id(self.intent_id, "intent_id")

    def digest(self) -> str:
        body = {
            "tenant": self.tenant,
            "miner": self.miner,
            "campaign_id": self.campaign_id,
            "intent_id": self.intent_id,
            "spec": self.spec.canonical(),
            "deadline_at": self.deadline_at,
        }
        raw = json.dumps(body, sort_keys=True, separators=(",", ":")).encode()
        return hashlib.sha256(raw).hexdigest()


@dataclass(frozen=True)
class Offer:
    """A provider price/stock observation, always with the time it was observed."""

    provider: str
    gpu_type_id: str
    gpu_count: int
    cloud_type: str
    usd_per_hr: float | None
    stock_status: str | None
    observed_at: float
    source: str


_STORE_ISSUED = object()


@dataclass(frozen=True)
class CarbonOwnedResource:
    """A provider resource whose intent Carbon persisted for this campaign.

    Constructible only by the store (it passes a module-private issuer token).
    """

    provider: str
    campaign_id: str
    intent_id: str
    resource_id: str
    ownership_tag: str
    _issuer: object = field(repr=False, compare=False, default=None)

    def __post_init__(self) -> None:
        if self._issuer is not _STORE_ISSUED:
            raise TypeError(
                "CarbonOwnedResource is issued only by ComputeStore from a "
                "Carbon-persisted intent"
            )
        _checked_id(self.resource_id, "resource_id")
        ownership_name(self.ownership_tag)

    @property
    def expected_name(self) -> str:
        return ownership_name(self.ownership_tag)


@dataclass(frozen=True)
class UserManagedHost:
    """A host the miner manages. Carbon may connect and health-check only.

    Deliberately has no stop/terminate capability and is refused by every
    termination path.
    """

    host_id: str
    address: str
    capabilities: tuple[str, ...] = ("connect", "health_check")

    def __post_init__(self) -> None:
        _checked_id(self.host_id, "host_id")
