"""The generated view of the pipeline: `docs/development/CHALLENGE_PIPELINE.md`.

`python -m carbon.challenge_pipeline render` writes it, and `--check` fails
when it is stale. Everything in it is computed from the families, the
protocol, the rubric and the records; nothing is typed in by hand.
"""

from __future__ import annotations

from carbon.challenge_pipeline.roadmap import board_rows, prerequisites_later, rank_all
from carbon.challenge_pipeline.state import (
    REPOSITORY,
    STAGE_LABELS,
    load_state,
    measured_times,
    stage_of,
)

DOCUMENT = REPOSITORY / "docs/development/CHALLENGE_PIPELINE.md"


def _time(seconds):
    if seconds < 60:
        return f"{seconds:g} s"
    if seconds < 3600:
        return f"{seconds / 60:g} min"
    return f"{seconds / 3600:g} h"


def _move(move):
    return "=" if move == 0 else (f"+{move}" if move > 0 else str(move))


def _pct(value):
    return "–" if value is None else f"{value * 100:.2f}%"


def render():
    families, protocol, rubric, records = load_state()
    names = {f["id"]: f["name"] for f in families["families"]}
    rows = rank_all(families, measured_times(records))
    late = prerequisites_later(rows, lambda fid: stage_of(records, fid))
    out = [
        "# Challenge pipeline: protocol, queue and leaderboard",
        "",
        "Generated by `python -m carbon.challenge_pipeline render`. Do not edit it by",
        "hand. The authority is `Design_Specs/Challenge_Roadmap.md` (rev 2.0), adopted",
        "by OWNER-CHALLENGE-ROADMAP-01. The state is in `carbon/challenge_pipeline/`:",
        "`families.json`, `protocol.json`, `rubric.json` and `records/`.",
        "",
        "**What this is not.** It is an internal development pipeline. A stage, a",
        "queue position or a leaderboard place is not scientific, security or",
        "production qualification, and no Challenge becomes LIVE or reward-bearing",
        "from it. Network activation stays a separate owner decision.",
        "",
        "## Protocol",
        "",
    ]
    if protocol["state"] == "LOCKED":
        out.append(
            f"Protocol {protocol['version']} is **locked** ({protocol['lock']['by']}, "
            f"{protocol['lock']['on']}, {protocol['lock']['ref']}); suite "
            f"{protocol['suite_version']}; reference hardware {protocol['reference_hardware']}."
        )
    else:
        out += [
            "**Phase 1: battery defines the protocol.** It is not locked, so no other",
            "family has entered the pipeline. Suite version, reference hardware and the",
            "protocol version are set during Phase 1 and approved at lock.",
        ]
    out += [
        "",
        "| Step | Work | Output | Ticket | Status |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in protocol["phase_1"]:
        work = s["work"] + (f" *{s['reserved']}*" if s["reserved"] else "")
        out.append(
            f"| {s['step']} | {work} | {s['output']} | {s['ticket'] or '–'} | {s['status']} |"
        )
    out += [
        "",
        "## Priority queue",
        "",
        "Three equally weighted 1–5 scores: workflow frequency, surrogate value and",
        "current solve time (under 1 s scores 1, 1–10 s 2, 10–60 s 3, 1–10 min 4,",
        "10 min or more 5). The composite is their mean; ties go to solve time, then",
        "value, then the v1.0 priority. A solve time is the v1-scope estimate until",
        "Design records a p50 on the reference hardware. Battery defines the",
        "protocol, so the first family to enter after lock is the highest-ranked",
        "other one.",
        "",
        "| Rank | Family | F | V | Solve time | S | Composite | Stage | vs v1.0 | Prerequisite later |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        fid = r["family"]["id"]
        solve = _time(r["t"]) + (" measured" if r["source"] == "measured" else " est.")
        later = ", ".join(names[n] for n in late[fid]) or "–"
        out.append(
            f"| {r['rank']} | {fid} {r['family']['name']} | {r['F']:g} | {r['V']:g} | "
            f"{solve} | {r['S']} | {r['composite']:.2f} | "
            f"{STAGE_LABELS[stage_of(records, fid)]} | {_move(r['move'])} | {later} |"
        )
    out += ["", "## Deployment leaderboard", ""]
    if all(rubric.get(key) is not None for key in ("minRho", "maxFF", "minN")):
        out.append(
            f"Rubric {rubric['version']} ({rubric['approved']['by']}, "
            f"{rubric['approved']['on']}): rank agreement at least {rubric['minRho']}, "
            f"false-feasible bound at most {rubric['maxFF']} %, at least {rubric['minN']} "
            f"independent scenarios"
            + (
                f", regret at most {rubric['maxReg']} %"
                if rubric["maxReg"] is not None
                else ""
            )
            + f"; open critical at most {rubric['maxC']}, open high at most {rubric['maxH']}."
        )
    else:
        out += [
            "**The rubric is not set.** The science owner proposes thresholds from",
            "battery's results and the process owner approves them as rubric v1 at",
            "protocol lock. Until then the leaderboard lists results without",
            "eligibility. Open critical and high findings: at most "
            + f"{rubric['maxC']} and {rubric['maxH']}.",
        ]
    board = board_rows(
        records, rubric, {r["family"]["id"]: r["composite"] for r in rows}
    )
    out.append("")
    if not board:
        out.append("No family has frozen Track A or B results yet.")
    else:
        out += [
            "| Position | Family | Stage | ρ | False-feasible bound | Regret | Open C/H/M/L | Suite | Not eligible because |",
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        for b in board:
            r = b["record"]
            counts = "/".join(
                "–" if r[k] is None else str(r[k])
                for k in ("attC", "attH", "attM", "attL")
            )
            out.append(
                f"| {b.get('position', '–')} | {b['fid']} {names[b['fid']]} | "
                f"{STAGE_LABELS[r['stage']]} | {'–' if r['rho'] is None else r['rho']} | "
                f"{_pct(b['ff'])} | {'–' if r['regret'] is None else str(r['regret']) + ' %'} | "
                f"{counts} | {r['suite']} | {'; '.join(b['why']) or '–'} |"
            )
    out += ["", "## Records", ""]
    for fid, r in records.items():
        prior = "; ".join(f"[{p['what']}]({_link(p['ref'])})" for p in r["prior_work"])
        out.append(
            f"- **{fid} {names[fid]}** ({STAGE_LABELS[r['stage']]}). {r['notes']}"
        )
        if prior:
            out.append(f"  Prior work: {prior}.")
    return "\n".join(out) + "\n"


def _link(ref):
    return "../../" + ref


def write(check=False):
    text = render()
    current = DOCUMENT.read_text(encoding="utf-8") if DOCUMENT.exists() else None
    if check:
        return current == text
    DOCUMENT.write_text(text, encoding="utf-8")
    return True
