apiVersion: v1
kind: Service
metadata:
  name: Carbon-validator
  labels:
    app: Carbon-validator
spec:
  selector:
    app: Carbon-validator
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
