'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const ROOT=path.resolve(__dirname,'..'),F=require('../src/engine.js'),E=require('../src/c05_evidence.js'),G=require('../src/workflow.js');
E.installFixtureIndex(JSON.parse(fs.readFileSync(path.join(ROOT,'data/c05_fixture_index_v1.json'))));
const atlas=JSON.parse(fs.readFileSync(path.join(ROOT,'data/atlas.json'))),ids=atlas.opportunities.map(x=>x.id),sha=atlas.source.sha256;
const clone=x=>JSON.parse(JSON.stringify(x));
function component(){return {schema_version:F.WORKSPACE_VERSION,application_version:F.APP_VERSION,source_sha256:sha,evidence_catalog:[],drafts:[],shortlist:[],migration_receipts:[]};}
function reader(raw){return F.readWorkspace(raw,ids,sha);}
function exactDesign(goal='Dynamics'){const j=G.newJob('job-001','Synthetic client job'),d=j.designs[0];Object.assign(d.scope,{physics_family:'periodic_viscous_burgers_1d_v1',requested_goal:goal,intended_use:'Use the public DEVELOPMENT Burgers template for a bounded semantic handoff without qualification or launch authority.',outputs:'Complete periodic field evolution',units:'source-defined nondimensional variables',rights_scope:'SYNTHETIC_INTERNAL'});return {j,d};}
function supportedDesign(){const {j,d}=exactDesign();Object.assign(d.scope,{inputs:'Finite Fourier initial field, viscosity and requested times',conditions:'Periodic, unforced, positive viscosity',query_workload:'Closed source-defined public campaign',turnaround:'No service limit established'});d.requirements=[G.requirement('REQ-1','Predict the full declared field evolution.','synthetic public demo','Decide whether the fixed source template preserves intent')];const t=G.trace('TRACE-1','REQ-1');Object.assign(t,{measurement_definition:'source measurement proposal',authoring_binding:'measurement_proposal',role:'MANDATORY',floor:'source DEVELOPMENT floor'});d.traces=[t];const c=G.caseFamily('CASE-1','EVAL');Object.assign(c,{requirement_ids:['REQ-1'],target_population:'source public Burgers population',sampling_frequency:'four parents per cell',analysis_weight:'one twelfth per cell',generator_ref:'goal_burgers_12cell_v1',support_status:'SOURCE_SUPPORTED'});d.cases=[c];Object.assign(d.score_plan,{mandatory_gate_summary:'Source mandatory physics precedes ranking',soft_estimand:'Source population-weighted quality proposal'});Object.assign(d.reference_plan,{equation:'u_t + d_x(u^2/2) = nu*u_xx',method:'source C-04 candidate and witness references'});return {j,d};}
function proposal(sourceGoal='Dynamics'){return {schema_version:'carbon.goal-authoring-proposal/1',challenge:{primary_goal:'Dynamics',competition_count:1},evidence_boundary:{source_goal:sourceGoal},physical_contract:{physical_scope:'SYNTHETIC_PERIODIC_VISCOUS_BURGERS_DEVELOPMENT_BENCHMARK'},capabilities:{archive_acknowledged:false,network_authorized:false,payout_authorized:false,registered:false,scientifically_qualified:false}};}
function authoringResult(d,request,p=proposal(request.requested_goal)){const receipt=G.semanticCompare(request,p,'sha256:proposal','sha256:input');return {schema_version:'carbon.goal-workbench.authoring-result.v1',request_id:request.request_id,job_id:d.job_id,design_id:d.design_id,design_revision:d.revision,input_digest:'sha256:input',proposal_digest:'sha256:proposal',proposal:p,cli_result:{status:'DEVELOPMENT_PROPOSAL'},semantic_receipt:receipt,source_revision:'source-test',route:'LOCAL_FIXED_CLI'};}
function response(d,h,overrides={}){return {schema_version:G.RESPONSE_VERSION,response_id:'response-1',request_id:h.request_id,base_revision:d.revision,job_id:d.job_id,design_id:d.design_id,design_revision:d.revision,kind:'ACKNOWLEDGMENT',route:'MANUAL',source_owner:'S1',status:'RECEIVED',output_reference:'manual-note',input_digest:'sha256:input',authority_class:'UNVERIFIED_ASSERTION',verification_reference:'',limitations:'No authority verification route',note:'<img src=x onerror=globalThis.pwned=true> inert text',content_sha256:'a'.repeat(64),...overrides};}
function legacyWorkspace(){const n=F.newDraft(ids[0],sha),fields=['schema_version','opportunity_id','source_sha256','planning_state','fit_checks','inputs','brief','reference_roles','reference_architecture','next_test','study_refs','review_note','evidence_status','qualification_status','submission_status','reuse_permission'],d={};for(const k of fields)d[k]=clone(n[k]);d.schema_version=F.LEGACY_DRAFT_VERSION;d.inputs.cohort='4';d.inputs.ref_lo='40';d.inputs.ref_hi='40';d.inputs.hardware='legacy synthetic profile';d.brief.notes='preserved client note';d.fit_checks.exam={state:'SUPPORTED_FOR_STAGE',evidence_note:'historical only'};return {schema_version:F.LEGACY_WORKSPACE_VERSION,source_sha256:sha,drafts:[d],shortlist:[ids[0]]};}

test('direct intake supports multiple jobs and alternatives without Atlas identity',()=>{const w=G.newWorkspace(component()),a=G.newJob('job-a','First'),b=G.newJob('job-b','Second');a.designs.push(G.newDesign('job-a','job-a-alt'));w.jobs.push(a,b);assert.equal(a.source_opportunity_id,null);assert.equal(w.jobs.length,2);assert.equal(a.designs.length,2);assert.deepEqual(G.validateWorkspace(w,reader).jobs.map(x=>x.job_id),['job-a','job-b']);});
test('v0.2 component migrates into empty v0.3 job layer without authority',()=>{const c=component(),d=F.newDraft(ids[0],sha);d.reference_economics.reference_work='40';d.protection.blockers['AT-09'].applicability='APPLICABLE';c.drafts=[d];const w=G.readWorkspace(JSON.stringify(c),reader,'VERIFIED_WEB_CRYPTO');assert.equal(w.jobs.length,0);assert.equal(w.opportunity_workspace.drafts[0].reference_economics.reference_work,'40');assert.equal(w.opportunity_workspace.drafts[0].protection.blockers['AT-09'].applicability,'APPLICABLE');assert.deepEqual(w.authority,G.AUTHORITY);});
test('v0.1 component migrates twice without losing notes or promoting old Exam support',()=>{const w=G.readWorkspace(JSON.stringify(legacyWorkspace()),reader);const d=w.opportunity_workspace.drafts[0];assert.equal(d.brief.notes,'preserved client note');assert.equal(d.legacy_sharing_scenario.cohort,'4');assert.equal(F.protectionReview(d).state,'UNASSESSED');assert.equal(w.migration_receipts.length,1);});
test('unsupported outer schema and forged authority reject',()=>{const w=G.newWorkspace(component());w.schema_version='carbon.goal-workbench.workspace.v9';assert.throws(()=>G.validateWorkspace(w,reader),/Unsupported/);const x=G.newWorkspace(component());x.authority.launch='LAUNCHED';assert.throws(()=>G.validateWorkspace(x,reader),/Authority promotion/);});
test('sealed design remains immutable and revision preserves history',()=>{const {j,d}=exactDesign();const next=G.reviseDesign(j,d.design_id,'job-001-design-2',[{field:'outputs',value:'New output'}]);assert.equal(d.status,'SEALED');assert.equal(d.scope.outputs,'Complete periodic field evolution');assert.equal(next.parent_design_id,d.design_id);assert.equal(next.scope.outputs,'New output');assert.throws(()=>G.applyChange(d,'units','changed'),/immutable/);});
test('material requirement requires a complete semantic trace and case binding',()=>{const {d}=exactDesign();d.requirements.push(G.requirement('REQ-1','A mandatory event must be resolved.','client note','A missed event invalidates the decision'));assert.deepEqual(G.coverage(d).missing_requirements,['REQ-1']);const t=G.trace('TRACE-1','REQ-1');Object.assign(t,{observable:'event peak',requested_output:'event time',measurement_definition:'declared operator',authoring_binding:'measurement:event',role:'MANDATORY',floor:'owner-supplied floor'});d.traces.push(t);assert.deepEqual(G.coverage(d).missing_case_requirements,['REQ-1']);const c=G.caseFamily('CASE-REQ-1','EVAL');c.requirement_ids=['REQ-1'];d.cases.push(c);assert.equal(G.coverage(d).status,'STRUCTURALLY_ASSEMBLED_NOT_NUMERICALLY_AUDITED');assert.equal(G.coverage(d).numerical_diagnostic,'NOT_EXECUTED_UNLESS_SOURCE_OWNED_RESULT_IS_BOUND');});
test('case coverage is audited in both directions',()=>{const {d}=supportedDesign();assert.deepEqual(G.coverage(d).missing_case_requirements,[]);d.cases[0].requirement_ids=[];let result=G.coverage(d);assert.deepEqual(result.missing_case_requirements,['REQ-1']);assert.deepEqual(result.orphan_case_families,['CASE-1']);d.cases[0].requirement_ids=['REQ-1'];d.traces[0].gap='measurement binding needs owner review';result=G.coverage(d);assert.deepEqual(result.case_families_without_complete_trace,['CASE-1']);assert.equal(result.status,'GAPS');});
test('mandatory failure cannot be offset by average and unresolved tradeoff has no rank',()=>{assert.equal(G.prospectivePreferenceDiagnostic('MANDATORY_FAILURE').expected_relation,'INELIGIBLE_REGARDLESS_OF_AVERAGE');assert.equal(G.prospectivePreferenceDiagnostic('PEAK_MISSED').expected_relation,'NO_TOTAL_RANK_WITHOUT_OWNER_TRADEOFF');assert.equal(G.prospectivePreferenceDiagnostic('PERSISTENCE_OR_MEMORIZATION').numerical_execution,'NOT_EXECUTED');assert.throws(()=>G.prospectivePreferenceDiagnostic('FAVORITE_WINS'));});
test('numerical diagnostic gap exports a bound strict C-05 reader request, not a scorer',()=>{const {d}=supportedDesign(),r=G.diagnosticRequest(d,'diagnostic-1');assert.equal(r.status,'NOT_EXECUTED');assert.equal(r.route,'LOCAL_STRICT_C05_READER');assert.equal(r.design_revision,d.revision);assert.equal(r.frozen_expectations.length,8);assert.equal(r.authority,'REQUEST_ONLY_NO_SCORER_EXECUTION_OR_QUALIFICATION');});
test('exact Dynamics route is callable and remains DEVELOPMENT-only',()=>{const {d}=supportedDesign(),r=G.authoringRequest(d,'author-1');assert.equal(r.route,'LOCAL_FIXED_CLI');assert.equal(r.compatibility.status,'EXACT_SUPPORTED');assert.equal(r.authority,'DEVELOPMENT_REQUEST_ONLY');assert.deepEqual(r.expected_semantics.sampling[0].generator_ref,'goal_burgers_12cell_v1');});
test('Front Resolution can call closed compiler but is not claimed compatible',()=>{const {d}=exactDesign('Front Resolution'),r=G.authoringRequest(d,'author-front'),receipt=G.semanticCompare(r,proposal('Front Resolution'),'sha256:p','sha256:i');assert.equal(r.route,'LOCAL_FIXED_CLI');assert.equal(r.compatibility.status,'EXTENSION_REQUIRED');assert.equal(receipt.status,'INTENT_MISMATCH');assert.match(receipt.mismatches[0],/Front Resolution emitted as Dynamics/);});
test('non-Burgers and client-rights scopes produce source-owner extension requests',()=>{const {d}=exactDesign();d.scope.physics_family='customer_heat_transfer_v1';d.scope.rights_scope='CLIENT_RESTRICTED';const r=G.authoringRequest(d,'author-gap');assert.equal(r.route,'SOURCE_OWNER_EXTENSION');assert.equal(d.authoring.extension_request.owner_interface,'C-AUTH1 scientific authoring owner');assert.match(d.authoring.extension_request.missing_capability,/customer_heat_transfer/);});
test('native result is rebound to exact originating design and receipt is recomputed',()=>{const {d}=supportedDesign(),r=G.authoringRequest(d,'author-1'),result=authoringResult(d,r);assert.equal(G.importAuthoringResult(d,r,result).status,'INTENT_PRESERVED');const stale=clone(result);stale.design_revision=2;assert.throws(()=>G.importAuthoringResult(d,r,stale),/Wrong or stale/);const forged=clone(result);forged.semantic_receipt.status='INTENT_MISMATCH';assert.throws(()=>G.importAuthoringResult(d,r,forged),/Forged/);});
test('handoff export is not send or execution and acknowledgement binds exactly',()=>{const {d}=exactDesign(),h=G.handoff(d,{request_id:'handoff-1',recipient:'S1',lead:'S1',question:'Is the exam meaning exact?',required_output:'Return scoped evidence',route:'MANUAL'});assert.equal(h.status,'PREPARED');assert.equal(G.markExported(d,h.request_id).status,'EXPORTED');assert.equal(d.decision.evidence_status,'PLANNED_OR_MISSING');const imported=G.importResponse(d,response(d,h));assert.equal(imported.authoritative,false);assert.equal(d.handoffs[0].status,'ACKNOWLEDGED');assert.equal(d.decision.scientific_qualification,'NOT_QUALIFIED');});
test('handoff requires one named lead',()=>{const {d}=exactDesign();assert.throws(()=>G.handoff(d,{request_id:'handoff-1',recipient:'S1',lead:'',question:'Question',required_output:'Output'}),/Invalid lead/);});
test('response duplicate deduplicates while conflict, stale, wrong-task and forged authority reject',()=>{const {d}=exactDesign(),h=G.handoff(d,{request_id:'handoff-1',recipient:'S1',lead:'S1',question:'Question',required_output:'Output'}),r=response(d,h);G.importResponse(d,r);assert.equal(G.importResponse(d,r).disposition,'DEDUPLICATED');assert.throws(()=>G.importResponse(d,{...r,content_sha256:'b'.repeat(64)}),/Conflicting/);assert.throws(()=>G.importResponse(d,response(d,h,{response_id:'stale',design_revision:2})),/stale/);assert.throws(()=>G.importResponse(d,response(d,h,{response_id:'wrong',job_id:'job-other'})),/stale/);assert.throws(()=>G.importResponse(d,response(d,h,{response_id:'forged',authority_class:'VERIFIED_OWNER_DECISION'})),/No trusted authority/);assert.equal(globalThis.pwned,undefined);});
test('design change invalidates only mapped downstream meanings and preserves old revision',()=>{const {j,d}=exactDesign();const next=G.reviseDesign(j,d.design_id,'job-001-design-2');const impact=G.applyChange(next,'units','dimensional SI output','client clarification');assert.deepEqual(impact,['measurement','normalization','reference','authoring','decision']);assert.equal(next.cpes.invalidated_by.length,0);G.applyChange(next,'physics_family','new_physics','scope change');assert.match(next.cpes.invalidated_by[0],/CPES/);assert.equal(d.scope.units,'source-defined nondimensional variables');});
test('favorable B scenario never changes baseline, blockers, qualification or launch',()=>{const {j,d}=exactDesign();Object.assign(d.cpes.economics,{reference_work:'40',reference_status:'user_assumed',group_overhead:'4',overhead_status:'user_assumed',group_size:'3',group_size_status:'user_assumed',unit:'synthetic work units',unit_scope:'unchanged adequate pack',compatible_demand_status:'user_assumed',field_dependent:'NO'});const p=G.engineeringProjection(j,d);assert.equal(p.conditional_economics.relation,'favorable');assert.equal(d.cpes.baseline,'RETAIN_A_DEVELOPMENT');assert.deepEqual(G.BLOCKERS,['AT-09','AT-16','AT-19','AT-22','AT-30']);assert.equal(p.launch_candidate.status,'MANUAL_OWNER_HANDOFF_REQUIRED');assert.equal(d.decision.scientific_qualification,'NOT_QUALIFIED');});
test('score or evidence-depth change preserves old inputs but makes economics stale',()=>{const {j,d}=exactDesign();Object.assign(d.cpes.economics,{reference_work:'40',reference_status:'user_assumed',group_overhead:'4',overhead_status:'user_assumed',group_size:'3',group_size_status:'user_assumed',unit:'synthetic work units',unit_scope:'unchanged adequate pack',compatible_demand_status:'user_assumed',field_dependent:'NO'});G.recordImpact(d,'score','measurement evidence depth changed');const p=G.engineeringProjection(j,d);assert.equal(p.conditional_economics.status,'STALE_FOR_REVIEW');assert.equal(p.conditional_economics.relation,'unknown');assert.equal(d.cpes.economics.reference_work,'40');assert.match(d.cpes.invalidated_by[0],/CPES economics/);});
test('launch status import cannot report LAUNCHED without trusted owner route',()=>{const {d}=exactDesign(),h=G.handoff(d,{request_id:'launch-1',recipient:'LAUNCH_OWNER',lead:'LAUNCH_OWNER',question:'Review candidate',required_output:'Native status'}),r=response(d,h,{response_id:'launch-response',kind:'LAUNCH_STATUS',status:'OWNER_ACKNOWLEDGED_LAUNCH'});G.importResponse(d,r);assert.equal(d.decision.native_launch_status,'NOT_LAUNCHED');const signed={...r,response_id:'signed-launch',authority_class:'VERIFIED_OWNER_DECISION',verification_reference:'trusted adapter'};assert.throws(()=>G.importResponse(d,signed),/No trusted authority/);});
test('client and N1 projections are least privilege',()=>{const {j,d}=exactDesign();j.assignment.rights_summary='private rights note';j.native_task_id='private-native-task';const client=G.clientProjection(j,d),n1=G.n1Projection(j,d);assert.equal(client.rights_summary,undefined);assert.equal(client.native_task_id,undefined);assert.equal(n1.native_task_id,undefined);assert.match(n1.excluded,/protected cases/);});
test('C-PILOT projection preserves supplied R1/S1 8/16 scope and triggers no training',()=>{const p=G.cPilotProjection();assert.equal(p.lead,'R1');assert.match(p.support,/S1/);assert.match(p.question,/8\/16/);assert.equal(p.training_triggered,false);assert.match(p.h1,/OPTIONAL/);});
