'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const F=require('../src/engine.js');
const A=JSON.parse(fs.readFileSync(__dirname+'/../data/atlas.json'));
const S=JSON.parse(fs.readFileSync(__dirname+'/../data/cpes_study_v1.json'));
const ids=A.opportunities.map(o=>o.id),sha=A.source.sha256;
const clone=v=>JSON.parse(JSON.stringify(v));
const base=()=>({...F.newDraft(ids[0],sha).inputs,hardware:'SYNTHETIC TEST: one homogeneous pool',daily_pool_hours:'1',supply_per_day:'',repetitions:'2',train_ref_lo:'3',train_ref_hi:'3',rebuild_lo:'10',rebuild_hi:'10',eval_lo:'5',eval_hi:'5',overhead_lo:'1',overhead_hi:'1',promotion_lo:'2',promotion_hi:'2',ref_lo:'60',ref_hi:'60',cohort:'4'});
const workspace=d=>({schema_version:F.WORKSPACE_VERSION,application_version:F.APP_VERSION,source_sha256:sha,evidence_catalog:[],drafts:[d],shortlist:[],migration_receipts:[]});
function legacyDraft(id=ids[0]){const n=F.newDraft(id,sha),keys=['schema_version','opportunity_id','source_sha256','planning_state','fit_checks','inputs','brief','reference_roles','reference_architecture','next_test','study_refs','review_note','evidence_status','qualification_status','submission_status','reuse_permission'],d={};for(const k of keys)d[k]=clone(n[k]);d.schema_version=F.LEGACY_DRAFT_VERSION;return d;}
const legacyWorkspace=d=>({schema_version:F.LEGACY_WORKSPACE_VERSION,source_sha256:sha,drafts:[d],shortlist:[d.opportunity_id]});
function econ(overrides={}){return {...F.newDraft(ids[0],sha).reference_economics,reference_work:'40',group_overhead:'4',group_size:'3',unit:'synthetic work units',unit_scope:'one unchanged adequate pack',reference_status:'user_assumed',overhead_status:'user_assumed',group_size_status:'user_assumed',compatible_demand_status:'user_assumed',field_dependent:'NO',...overrides};}

test('empty legacy capacity inputs remain unknown',()=>assert.equal(F.profile({}).status,'INPUT_REQUIRED_OR_INVALID'));
test('legacy shared-work arithmetic remains stable and explicitly scenario-only',()=>{const r=F.profile(base());assert.equal(r.capacity_lower,72);assert.equal(r.capacity_upper,72);assert.deepEqual(r.per_candidate_seconds,[34,34]);assert.deepEqual(r.full_cohort_seconds,[196,196]);assert.equal(r.validator_count,1);assert.match(r.note,/Legacy hypothetical/);});
test('legacy last partial cohort is charged in full',()=>assert.equal(F.maxCompleted(175,10,100,4),4));
test('legacy exact budget equality is allowed',()=>assert.equal(F.maxCompleted(140,10,100,4),4));
test('legacy one-below boundary rejects fourth item',()=>assert.equal(F.maxCompleted(139,10,100,4),3));
test('legacy interval bounds remain stable',()=>{const r=F.profile({...base(),rebuild_hi:'20'});assert.deepEqual([r.capacity_lower,r.capacity_upper],[52,72]);});
test('upfront qualification never enters recurring capacity',()=>assert.deepEqual(F.profile(base()),F.profile({...base(),qualification_cost:'9000000',qualification_days:'900'})));
test('legacy supply caps counts, not work',()=>assert.equal(F.profile({...base(),supply_per_day:'10'}).capacity_upper,10));
test('legacy zero supply remains zero',()=>assert.equal(F.profile({...base(),supply_per_day:'0'}).capacity_upper,0));
test('legacy cohort one does not share',()=>assert.equal(F.profile({...base(),cohort:'1'}).capacity_upper,38));
test('explicit zero legacy overhead is measured absence, not missing',()=>assert.equal(F.profile({...base(),overhead_lo:'0',overhead_hi:'0'}).status,'SCENARIO_ONLY'));
for(const [k,v] of [['rebuild_lo','-1'],['rebuild_hi','NaN'],['daily_pool_hours','Infinity'],['repetitions','1.5'],['cohort','0'],['ref_hi',''],['supply_per_day','2.5'],['rebuild_lo','11']])test('legacy invalid input rejects '+k+'='+v,()=>assert.equal(F.profile({...base(),[k]:v}).status,'INPUT_REQUIRED_OR_INVALID'));
test('hardware description is required',()=>assert.equal(F.profile({...base(),hardware:''}).status,'INPUT_REQUIRED_OR_INVALID'));
test('strict and inclusive planning comparators differ at equality',()=>{assert.equal(F.margin(2,2,'<').within,false);assert.equal(F.margin(2,2,'<=').within,true);});
test('boolean and unsafe integer numeric coercions reject',()=>{assert.throws(()=>F.number(true,'test'));assert.throws(()=>F.number('9007199254740992','test',{integer:true}));});

test('fixed group exact vector b=3 R=40 H=4',()=>{const r=F.fixedGroupEconomics(econ());assert.equal(r.a_reference_control_work,120);assert.equal(r.b_reference_control_work,44);assert.equal(r.net_saving_per_group,76);assert.equal(r.net_saving_per_candidate,76/3);assert.equal(r.relation,'favorable');assert.equal(r.baseline,'RETAIN_A');assert.equal(r.runtime_sharing_authorized,false);});
test('fixed group b=1 charges unavoidable overhead and never divides by b-1',()=>{const r=F.fixedGroupEconomics(econ({group_size:'1'}));assert.equal(r.relation,'no_sharing_opportunity');assert.equal(r.net_saving_per_group,-4);assert.equal(r.break_even_reference_work,null);});
test('fixed group equality is break-even not advantage',()=>{const r=F.fixedGroupEconomics(econ({reference_work:'2',group_overhead:'4'}));assert.equal(r.net_saving_per_group,0);assert.equal(r.relation,'equal');});
test('fixed group negative saving is unfavorable',()=>assert.equal(F.fixedGroupEconomics(econ({reference_work:'1',group_overhead:'5'})).relation,'unfavorable'));
test('zero reference work stays measured zero and charges overhead',()=>{const r=F.fixedGroupEconomics(econ({reference_work:'0'}));assert.equal(r.status,'CALCULATED_CONDITIONAL');assert.equal(r.net_saving_per_group,-4);});
test('invalid group size rejects',()=>{assert.equal(F.fixedGroupEconomics(econ({group_size:'0'})).status,'INVALID');assert.equal(F.fixedGroupEconomics(econ({group_size:'1.5'})).status,'INVALID');});
for(const key of ['reference_work','group_overhead','group_size','unit','unit_scope'])test('missing '+key+' keeps dependent economics unknown',()=>{const r=F.fixedGroupEconomics(econ({[key]:''}));assert.equal(r.status,'UNKNOWN');assert.equal(r.relation,'unknown');});
test('unknown compatible demand preserves conditional arithmetic but not feasibility',()=>{const r=F.fixedGroupEconomics(econ({compatible_demand_status:'unknown'}));assert.equal(r.relation,'favorable');assert.ok(r.unknowns.includes('compatible demand at dispatch'));assert.equal(r.conditional,true);});
test('configured maximum alone cannot establish dispatch coexistence',()=>{const r=F.fixedGroupEconomics(econ({group_size_status:'user_assumed',compatible_demand_status:'unknown',compatible_demand_source:'configured maximum 3'}));assert.ok(r.unknowns.includes('compatible demand at dispatch'));});
test('field-dependent reference need keeps fixed-R result conditional',()=>{const r=F.fixedGroupEconomics(econ({field_dependent:'YES'}));assert.equal(r.conditional,true);assert.ok(r.unknowns.includes('field-dependent evidence requirement'));});
test('workspace import rejects an undeclared or malformed unit',()=>{const d=F.newDraft(ids[0],sha);d.reference_economics=econ({unit:'seconds per GPU plus dollars'});assert.throws(()=>F.readWorkspace(JSON.stringify(workspace(d)),ids,sha),/unit/);});
test('aggregate charges underfilled groups and divides by completions',()=>assert.deepEqual(F.aggregateGroups([{reference_work:40,overhead:4,completed:3},{reference_work:40,overhead:4,completed:1}]),{total_reference_control_work:88,completed_comparisons:4,cost_per_completion:22,status:'CALCULATED'}));
test('empty and zero-completion aggregate costs are undefined, never zero',()=>{assert.equal(F.aggregateGroups([]).cost_per_completion,null);assert.equal(F.aggregateGroups([{reference_work:40,overhead:4,completed:0}]).status,'UNDEFINED_ZERO_COMPLETIONS');});
test('cross-unit, cross-host and timing-boundary composition rejects',()=>{const q={value:'3',unit:'CPU seconds',scope:'one pack',environment:'Linux worker',timing_boundary:'active resource occupancy',status:'observed'};assert.throws(()=>F.composeQuantities(q,{...q,unit:'GPU seconds'}),/different units/);assert.throws(()=>F.composeQuantities(q,{...q,environment:'Apple M3'}),/cross-environment/);assert.throws(()=>F.composeQuantities(q,{...q,timing_boundary:'wall latency'}),/wall latency/);});
test('compatible quantity composition is explicit and scoped',()=>{const q={value:'3',unit:'CPU seconds',scope:'one pack',environment:'Linux worker',timing_boundary:'active resource occupancy',status:'observed'};assert.equal(F.composeQuantities(q,{...q,value:'4'}).value,7);});
test('upfront fields do not change economics relation or baseline',()=>{const a=F.fixedGroupEconomics(econ()),b=F.fixedGroupEconomics(econ({upfront_cost:'999999',upfront_duration:'500 days',upfront_risk:'high'}));assert.equal(a.relation,b.relation);assert.equal(b.baseline,'RETAIN_A');});

test('endogenous grouping counterexample remains exact',()=>{assert.deepEqual(S.dynamic.counterexample.h0,{groups:[['a'],['b'],['c','d']],work:38,c_d_release:39});assert.deepEqual(S.dynamic.counterexample.h4,{groups:[['a'],['b','c','d']],work:36,c_d_release:36});});
test('slow member retains fewer summaries alongside lower work',()=>{const rows=S.dynamic.rows.filter(r=>r.scenario==='slow_or_unresolved_member'&&r.assumed_group_overhead===0),a=rows.find(r=>r.variant==='A'),b=rows.find(r=>r.variant==='B');assert.equal(a.complete_comparisons,3);assert.equal(b.complete_comparisons,1);assert.ok(b.total_recurring_work<a.total_recurring_work);const d=F.newDraft(ids[0],sha);d.dynamic_scenario={scenario:'slow_or_unresolved_member',overhead:'0'};assert.match(F.selectedDynamic(d,S).warning,/not equivalent productive throughput/);});
test('C remains sensitivity-only in the pinned scenario',()=>{const d=F.newDraft(ids[0],sha),r=F.selectedDynamic(d,S);assert.ok(r.rows.some(x=>x.variant==='C'));assert.equal(S.variant_c,'RESEARCH_SENSITIVITY_ONLY_NOT_RECOMMENDED');});

test('new protection information starts UNASSESSED not passed',()=>{const d=F.newDraft(ids[0],sha),r=F.protectionReview(d);assert.equal(r.state,'UNASSESSED');assert.equal(r.qualified,false);assert.deepEqual(r.unresolved_blockers,F.BLOCKER_IDS);});
test('old supported Exam note cannot erase protection status',()=>{const d=F.newDraft(ids[0],sha);d.fit_checks.exam={state:'SUPPORTED_FOR_STAGE',evidence_note:'Historical user note'};assert.equal(F.protectionReview(d).state,'UNASSESSED');assert.deepEqual(F.protectionReview(d).unresolved_blockers,F.BLOCKER_IDS);});
test('applicable demonstrated blocker yields PROTECTION_BLOCKED',()=>{const d=F.newDraft(ids[0],sha);d.protection.blockers['AT-09'].applicability='APPLICABLE';assert.equal(F.protectionReview(d).state,'PROTECTION_BLOCKED');});
test('complete packet can be READY_FOR_DOMAIN_REVIEW but never qualified',()=>{const d=F.newDraft(ids[0],sha),filled={source_reference:'owner record',reviewer_notes:'scoped assertion',measurement_method:'reviewed',unresolved_assumptions:''};for(const id of F.CONTROL_IDS)d.protection.controls[id]={state:'EVIDENCE_ASSEMBLED',...filled};for(const id of F.BLOCKER_IDS)d.protection.blockers[id]={applicability:'NOT_APPLICABLE_ASSERTED',...filled};const r=F.protectionReview(d);assert.equal(r.state,'READY_FOR_DOMAIN_REVIEW');assert.equal(r.qualified,false);});
test('complete record can still display unresolved applicable risk',()=>{const d=F.newDraft(ids[0],sha),filled={source_reference:'owner record',reviewer_notes:'scoped assertion',measurement_method:'reviewed',unresolved_assumptions:''};for(const id of F.CONTROL_IDS)d.protection.controls[id]={state:'EVIDENCE_ASSEMBLED',...filled};for(const id of F.BLOCKER_IDS)d.protection.blockers[id]={applicability:'NOT_APPLICABLE_ASSERTED',...filled};d.protection.blockers['AT-16'].applicability='APPLICABLE';const r=F.protectionReview(d);assert.equal(r.record_complete,true);assert.equal(r.state,'PROTECTION_BLOCKED');assert.ok(r.unresolved_blockers.includes('AT-16'));});

test('v0.2 workspace round trip validates and preserves record',()=>{const w=workspace(F.newDraft(ids[0],sha));assert.deepEqual(F.readWorkspace(JSON.stringify(w),ids,sha),w);});
test('substantive v0.1 workspace migrates additively without authority promotion',()=>{const d=legacyDraft();d.inputs.cohort='7';d.inputs.ref_lo='40';d.inputs.ref_hi='50';d.inputs.hardware='Historical M3 scenario';d.brief.notes='Keep this substantive note';d.brief.contact='private@example.test';d.fit_checks.exam={state:'SUPPORTED_FOR_STAGE',evidence_note:'Historical support note'};d.reference_roles=['routine_exam','independent_witness'];d.reference_architecture.independent_witness.evidence_note='Distinct witness';d.next_test='Bounded next test';d.study_refs=['old-study'];d.review_note='Reviewer context';const w=F.readWorkspace(JSON.stringify(legacyWorkspace(d)),ids,sha,{originalSha:'a'.repeat(64),digestStatus:'VERIFIED_WEB_CRYPTO'}),m=w.drafts[0];assert.equal(m.brief.notes,d.brief.notes);assert.equal(m.brief.contact,d.brief.contact);assert.deepEqual(m.reference_roles,d.reference_roles);assert.equal(m.reference_architecture.independent_witness.evidence_note,'Distinct witness');assert.equal(m.fit_checks.exam.evidence_note,'Historical support note');assert.equal(m.legacy_sharing_scenario.cohort,'7');assert.equal(m.evidence_status,F.AUTHORITY.evidence_status);assert.equal(F.protectionReview(m).state,'UNASSESSED');assert.deepEqual(F.legacyBaselineA(m).reference_work_per_admitted_job,[40,50]);});
test('all 64 source identities survive independent legacy migration',()=>{for(const id of ids){const w=F.readWorkspace(JSON.stringify(legacyWorkspace(legacyDraft(id))),ids,sha);assert.equal(w.drafts[0].opportunity_id,id);}});
test('export and reimport recomputes identical planning result',()=>{const d=F.newDraft(ids[0],sha);d.reference_economics=econ();const before=F.analysisRecord(d,S),w=F.readWorkspace(JSON.stringify(workspace(d)),ids,sha),after=F.analysisRecord(w.drafts[0],S);assert.deepEqual(after,before);});
test('forged precomputed recommendation is rejected',()=>{const d=F.newDraft(ids[0],sha);d.recommendation='RECOMMEND_B';assert.throws(()=>F.readWorkspace(JSON.stringify(workspace(d)),ids,sha));});
test('authority fields can never be promoted by import',()=>{for(const [k,v] of [['qualification_status','QUALIFIED'],['submission_status','SENT'],['reuse_permission','GRANTED'],['evidence_status','QCE']]){const d=F.newDraft(ids[0],sha);d[k]=v;assert.throws(()=>F.readWorkspace(JSON.stringify(workspace(d)),ids,sha));}});
test('modified source identity, unknown source ID and duplicate draft reject',()=>{let w=workspace(F.newDraft(ids[0],sha));w.source_sha256='wrong';assert.throws(()=>F.readWorkspace(JSON.stringify(w),ids,sha));w=workspace(F.newDraft(ids[0],sha));w.drafts[0].opportunity_id='bad';assert.throws(()=>F.readWorkspace(JSON.stringify(w),ids,sha));w=workspace(F.newDraft(ids[0],sha));w.drafts.push(clone(w.drafts[0]));assert.throws(()=>F.readWorkspace(JSON.stringify(w),ids,sha));});
test('conflicting newer and malformed schemas fail without mutating current object',()=>{const current=workspace(F.newDraft(ids[0],sha)),snapshot=JSON.stringify(current),incoming=clone(current);incoming.schema_version='carbon_workbench_workspace_v9';assert.throws(()=>F.readWorkspace(JSON.stringify(incoming),ids,sha));assert.equal(JSON.stringify(current),snapshot);assert.throws(()=>F.readWorkspace('{"schema_version":',ids,sha));});
test('workspace migration receipt is closed and validated',()=>{const w=workspace(F.newDraft(ids[0],sha));w.migration_receipts=[{from:F.LEGACY_WORKSPACE_VERSION,to:F.WORKSPACE_VERSION,original_sha256:'',digest_status:'UNAVAILABLE',semantic_changes:['migration']}];assert.equal(F.readWorkspace(JSON.stringify(w),ids,sha).migration_receipts.length,1);w.migration_receipts[0].authority='APPROVED';assert.throws(()=>F.readWorkspace(JSON.stringify(w),ids,sha));});

test('strict parser rejects duplicate members, pollution keys and nesting',()=>{assert.throws(()=>F.strictJsonParse('{"a":1,"a":2}'),/duplicate/);assert.throws(()=>F.strictJsonParse('{"__proto__":{}}'),/forbidden/);assert.throws(()=>F.strictJsonParse('['.repeat(26)+'0'+']'.repeat(26)),/nesting/);});
test('strict parser rejects overflow and Boolean-as-number downstream',()=>{assert.throws(()=>F.strictJsonParse('{"x":1e999}'),/nonfinite/);assert.throws(()=>F.strictJsonParse('{"x":9007199254740992}'),/unsafe/);assert.equal(F.fixedGroupEconomics({...econ(),group_size:true}).status,'INVALID');});
test('bounded imported claim accepts inert text but rejects authority fields',()=>{const c={schema_version:'carbon.workbench.cpes-study-import.v1',study_id:'user-study',evidence_version:'v1',recommendation:'RECOMMEND_B <script>alert(1)</script>',source_reference:'data:text/html,bad',delivery_status:'self-authored',qualified_carbon_evidence:null,content_sha256:'a'.repeat(64)};assert.match(F.validateEvidenceClaim(c).recommendation,/<script>/);assert.throws(()=>F.validateEvidenceClaim({...c,authority:'APPROVED'}));assert.throws(()=>F.validateEvidenceClaim({...c,qualification_id:'Q-1'}));});
test('duplicate evidence versions conflict at workspace boundary',()=>{const c={schema_version:'carbon.workbench.cpes-study-import.v1',study_id:'user-study',evidence_version:'v1',recommendation:'RECOMMEND_B',source_reference:'local',delivery_status:'self-authored',qualified_carbon_evidence:null,content_sha256:'a'.repeat(64)},w=workspace(F.newDraft(ids[0],sha));w.evidence_catalog=[c,{...c,content_sha256:'b'.repeat(64)}];assert.throws(()=>F.readWorkspace(JSON.stringify(w),ids,sha),/Duplicate evidence versions/);});
test('exports preserve baseline, blockers, unknowns and null qualification',()=>{const d=F.newDraft(ids[0],sha);d.brief.contact='private@example.test';d.brief.notes='public-safe note';const c=F.clientProjection(d,S,'Title'),e=F.engineeringProjection(d,S,'Title');assert.match(c.current_recommendation,/Variant A/);assert.equal(c.client_context.contact,undefined);assert.deepEqual(c.unresolved_protection,F.BLOCKER_IDS);assert.equal(c.study_reference.qualified_carbon_evidence,null);assert.equal(e.analysis.current_baseline.variant,'A');assert.deepEqual(e.study_blockers.map(x=>x.attack_id),F.BLOCKER_IDS);assert.equal(e.all_attack_refs.length,30);assert.match(e.authority,/cannot implement or activate/);});
test('markdown exports include authority and scenario caveats',()=>{const d=F.newDraft(ids[0],sha);d.reference_economics=econ();const md=F.markdownProjection(F.clientProjection(d,S,'Title'));assert.match(md,/planning summary only/);assert.match(md,/RETAIN_A/);assert.match(md,/conditional/i);});
