'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),F=require('../src/engine.js'),E=require('../src/c05_evidence.js'),G=require('../src/workflow.js');
const index=JSON.parse(fs.readFileSync(path.join(ROOT,'data/c05_fixture_index_v1.json'))),complete=fs.readFileSync(path.join(ROOT,'data/c05_public_development_evidence_v1.json'),'utf8'),noncomplete=fs.readFileSync(path.join(ROOT,'data/c05_public_development_noncomplete_v1.json'),'utf8');
const sha=async raw=>crypto.createHash('sha256').update(raw).digest('hex'),clone=x=>JSON.parse(JSON.stringify(x));
E.installFixtureIndex(index);
function context(){const j=G.newJob('job-001','C-05 integration'),d=j.designs[0];d.scope.physics_family='periodic_viscous_burgers_1d_v1';d.requirements=[G.requirement('REQ-DYNAMICS','Predict complete field evolution.','public fixture','Inform bounded design')];const t=G.trace('TRACE-DYNAMICS','REQ-DYNAMICS');Object.assign(t,{measurement_definition:'source C-05 measurement',authoring_binding:'carbon.goal-authoring-proposal/1',role:'MANDATORY',floor:'source-owned DEVELOPMENT normalization only'});d.traces=[t];const c=G.caseFamily('BURGERS-12-CELL','EVAL');Object.assign(c,{requirement_ids:['REQ-DYNAMICS'],generator_ref:'goal_burgers_12cell_v1',support_status:'SOURCE_SUPPORTED'});d.cases=[c];return {j,d,request:G.diagnosticRequest(d,'diagnostic-job-001-design-1-r1')};}
async function imported(raw=complete){const x=context(),result=await E.importBundle(x.d,x.request,raw,sha);return {...x,result,record:result.record};}
function mutate(raw,fn){const value=JSON.parse(raw);fn(value);return JSON.stringify(value);}
test('imports exact source-owned C-05 bundle',async()=>assert.equal((await imported()).result.disposition,'IMPORTED'));
test('retains exact four measurement IDs',async()=>assert.deepEqual((await imported()).record.measurements.map(x=>x.measurement_id),E.MEASUREMENTS));
test('retains exact six physics IDs',async()=>assert.deepEqual((await imported()).record.physics.map(x=>x.physics_id),E.PHYSICS));
test('retains raw candidate/reference/error/scales and unresolved decisions',async()=>{const r=(await imported()).record;assert.ok(r.measurements.every(x=>Number.isFinite(x.candidate_value)&&Number.isFinite(x.reference_value)&&x.scientific_limit===null&&x.uncertainty===null&&x.decision==='UNRESOLVED_NO_QUALIFIED_LIMIT'));});
test('binds source evidence into both trace directions',async()=>{const {d}=await imported(),c=G.coverage(d);assert.equal(c.trace_evidence[0].source_execution,'SOURCE_MEASUREMENT_EXECUTED');assert.equal(c.status,'STRUCTURALLY_ASSEMBLED_WITH_SOURCE_MEASUREMENT_EVIDENCE');});
test('client projection remains least privilege',async()=>{const {j,d}=await imported(),p=G.clientProjection(j,d);assert.equal(p.source_measurement_evidence[0].scientific_decision,'UNRESOLVED');assert.equal(JSON.stringify(p).includes('candidate_value'),false);});
test('engineering projection retains full provenance and observations',async()=>{const {j,d}=await imported(),p=G.engineeringProjection(j,d);assert.equal(p.design.measurement_evidence[0].source.result_schema,E.RESULT_SCHEMA);assert.equal(p.design.measurement_evidence[0].physics.length,6);});
test('exact replay deduplicates',async()=>{const {d,request}=await imported();assert.equal((await E.importBundle(d,request,complete,sha)).disposition,'DEDUPLICATED');});
test('same source identity with changed outer bytes conflicts',async()=>{const {d,request}=await imported();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>x.limitations[0]+=' changed'),sha),/changed bytes conflict/);});
for(const [name,fn] of [['job',x=>x.association.job_id='other'],['design',x=>x.association.design_id='other'],['revision',x=>x.association.design_revision=2],['request',x=>x.association.request_id='other']])test('rejects wrong '+name,async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,fn),sha),/REJECTED/);});
test('rejects wrong source result schema',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>x.source.result_schema='wrong'),sha),/wrong source schema/);});
test('rejects candidate provenance laundering',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>{const q=JSON.parse(x.measurement_request_json);q.candidate.source_digest='sha256:'+'e'.repeat(64);x.measurement_request_json=JSON.stringify(q);}),sha),/REJECTED/);});
test('registered result cannot be manually rebound to an unrelated compatible-looking case family',async()=>{const {d,request}=context();d.cases[0].case_family_id='OTHER-PUBLIC-CASE';request.source_association.case_family_ids=['OTHER-PUBLIC-CASE'];const rebound=mutate(complete,x=>x.association.case_family_ids=['OTHER-PUBLIC-CASE']);await assert.rejects(E.importBundle(d,request,rebound,sha),/registered manual fixture association/);});
test('rejects unknown adapter schema',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>x.schema_version='v2'),sha),/unknown adapter schema/);});
test('rejects duplicate or reordered observation IDs',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>{const q=JSON.parse(x.measurement_result_json);q.measurements[1].measurement_id=q.measurements[0].measurement_id;x.measurement_result_json=JSON.stringify(q);}),sha),/REJECTED/);});
test('retains typed non-complete disposition without observations',async()=>{const {record}=await imported(noncomplete);assert.equal(record.evidence_state,'SOURCE_MEASUREMENT_EVIDENCE_NOT_EXECUTED');assert.equal(record.measurements.length,0);assert.equal(record.source_disposition,'NUMERICAL_FAILURE');});
test('strict parser rejects nonfinite token',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,complete.replace('0.0001','NaN'),sha),/REJECTED|non-canonical|Invalid JSON/);});
test('forged qualification authority rejects',async()=>{const {d,request}=context();await assert.rejects(E.importBundle(d,request,mutate(complete,x=>x.authority.scientifically_qualified=true),sha),/authority/);});
test('new design revision starts without current evidence and preserves old revision',async()=>{const {j,d}=await imported();const next=G.reviseDesign(j,d.design_id,'job-001-design-1-r2');assert.equal(d.measurement_evidence.length,1);assert.equal(next.measurement_evidence.length,0);});
test('semantic edit stales evidence while unrelated note does not',async()=>{const {d}=await imported();G.recordImpact(d,'commercial_note','editorial');assert.equal(d.measurement_evidence[0].binding_status,'CURRENT_DESIGN_REVISION');G.recordImpact(d,'score','scientific meaning changed');assert.equal(d.measurement_evidence[0].binding_status,'STALE_DESIGN_CHANGED');});
test('evidence import cannot change CPES baseline blockers or authority',async()=>{const {d,record}=await imported();assert.equal(d.cpes.baseline,'RETAIN_A_DEVELOPMENT');assert.deepEqual(G.BLOCKERS,['AT-09','AT-16','AT-19','AT-22','AT-30']);assert.equal(record.score_eligible,false);assert.equal(record.approved,false);assert.equal(record.launch_authorized,false);});
test('behavior matrix classifies all eight without claiming execution',async()=>{const {record}=await imported();assert.equal(record.behavior_classification.length,8);assert.ok(record.behavior_classification.some(x=>x.classification==='REQUIRES_SCOREPACK_DIAGNOSTIC_CONTRACT'));});
