"""B-E4 fixture-engineering gauntlet with no qualification authority."""

from .design import (
    DECISION_RULE_ID,
    DESIGN_AUTHORITY_CEILING,
    DESIGN_DOCUMENT_HEADER,
    DESIGN_SCHEMA_VERSION,
    DESIGN_STATUS,
    DIVERSITY_METRIC_ID,
    PRIMARY_ESTIMAND_ID,
    PROTECTED_TARGETS,
    REQUIRED_DESIGN_INPUTS,
    REQUIRED_RATIFYING_OWNERS,
    CanonicalIntervention,
    DesignAnalysisClassification,
    DesignDocumentError,
    IntervalBound,
    InterventionDiversityAnalysis,
    LeakageTargetBound,
    PowerDesignAnalysis,
    ProposedGauntletDesign,
    UtilityContrastBound,
    analytic_joint_leakage_clearance,
    analytic_joint_utility_power,
    analyze_intervention_diversity,
    classify_diversity_boundary,
    classify_leakage_boundary,
    classify_utility_boundary,
    complete_block_retention_probability,
    compose_design_analysis_gates,
    fixture_resolution_quality,
    parse_proposed_design,
    required_replicates_per_profile,
    run_nonqualifying_power_analysis,
)
from .harness import (
    AgentDriver,
    AgentSession,
    GauntletPreflightError,
    validate_experiment_matrix,
    validate_integrity_matrix,
)
from .model import *
from .shadow import HeldoutToyShadowCases

__all__ = (
    "DECISION_RULE_ID",
    "DESIGN_AUTHORITY_CEILING",
    "DESIGN_DOCUMENT_HEADER",
    "DESIGN_SCHEMA_VERSION",
    "DESIGN_STATUS",
    "DIVERSITY_METRIC_ID",
    "PRIMARY_ESTIMAND_ID",
    "PROTECTED_TARGETS",
    "REQUIRED_DESIGN_INPUTS",
    "REQUIRED_RATIFYING_OWNERS",
    "AgentDriver",
    "AgentSession",
    "CanonicalIntervention",
    "DesignAnalysisClassification",
    "DesignDocumentError",
    "GauntletPreflightError",
    "HeldoutToyShadowCases",
    "IntervalBound",
    "InterventionDiversityAnalysis",
    "LeakageTargetBound",
    "PowerDesignAnalysis",
    "ProposedGauntletDesign",
    "UtilityContrastBound",
    "analytic_joint_leakage_clearance",
    "analytic_joint_utility_power",
    "analyze_intervention_diversity",
    "classify_diversity_boundary",
    "classify_leakage_boundary",
    "classify_utility_boundary",
    "complete_block_retention_probability",
    "compose_design_analysis_gates",
    "fixture_resolution_quality",
    "parse_proposed_design",
    "required_replicates_per_profile",
    "run_nonqualifying_power_analysis",
    "validate_experiment_matrix",
    "validate_integrity_matrix",
)
