"""The motor reference's GetDP input: a 2D magnetostatic a-formulation.

Written by Carbon from GetDP's documented language, for the meshes
`carbon.motor.mesh` writes (region tags there). For each rotor position:

    curl(nu curl a) = js + curl(nu br),   a = 0 on the stator's outer circle

- **Materials:** air, coils and shaft at mu0; magnets with recoil
  permeability `mur_m` and a radial remanence of +-`br` alternating by pole;
  iron linear (`mur_fe`) or nonlinear (`nu(b^2)`, solved by Newton-Raphson
  with the exact derivative).
- **Sources:** each coil carries `turns * I_phase / coil_area`, with the
  slot's phase and sign from the winding table.
- **Torque, two ways:**
  - Arkkio's Maxwell stress over the airgap annulus between rotor surface and
    bore (regions 3 and 13, both exact annuli):
    T = L / (mu0 (r_si - r_ro)) * integral of r B_r B_theta dS;
  - co-energy, for the virtual-work check, W' = L * integral of the
    co-energy density. For linear materials that is 1/2 nu |b|^2 (up to a
    constant that does not move with the rotor), so
    T = dW'/dtheta at fixed currents.
- **Flux linkage:** each coil's mean `a`, for the phase flux linkages.

Outputs go to `res/<quantity>_<STEP>.txt`, one file per rotor step.
"""

from __future__ import annotations

import math

MU0 = "4e-7*Pi"
#: Nonlinear solver settings, on the relative solution increment: damped
#: Newton to DAMPED_TOL, then full Newton to NEWTON_TOL. The pilot's first
#: attempt asked 1e-8 and found rotor positions stalling near 4e-7, a floor
#: this problem reaches; torque agrees to 1e-11 across 1e-8 and 1e-6 where
#: both converge, three orders below the mesh's error (rung M1).
DAMPED_MAX, DAMPED_TOL, DAMPING = 40, 1e-3, 0.5
NEWTON_MAX, NEWTON_TOL = 30, 1e-6
REGIONS = {
    "shaft": 1,
    "rotor_fe": 2,
    "rotor_gap": 3,
    "rotor_air": 4,
    "stator_fe": 11,
    "stator_gap": 13,
    "slot_air": 14,
    "magnet0": 101,
    "coil0": 201,
    "outer": 1000,
}


def winding(slots, poles):
    """(phase, sign) per slot for a single-layer winding with one slot per
    pole per phase: A+, C-, B+, A-, C+, B- repeating."""
    if slots != 3 * poles:
        raise ValueError("this winding needs one slot per pole per phase")
    pattern = [("A", 1), ("C", -1), ("B", 1), ("A", -1), ("C", 1), ("B", -1)]
    return [pattern[k % 6] for k in range(slots)]


def pro_text(p, *, nonlinear=None):
    """The .pro file for machine parameters `p` (lengths in mm).

    `nonlinear` is None for linear iron, or (nu0_coefficient, k1, k2) for the
    iron law nu(b^2) = nu0_coefficient * mu0^-1 ... see `_iron`."""
    poles, slots = p["poles"], p["slots"]
    r = REGIONS
    magnets = [r["magnet0"] + k for k in range(poles)]
    coils = [r["coil0"] + k for k in range(slots)]
    table = winding(slots, poles)
    mm = 1e-3
    lines = []
    w = lines.append
    w("// Carbon motor reference (#344): generated by carbon/motor/getdp.py")
    w("DefineConstant[ IA = 0, IB = 0, IC = 0, STEP = 0 ];")
    w("Group {")
    w(f"  Shaft = Region[{r['shaft']}]; RotorFe = Region[{r['rotor_fe']}];")
    w(f"  RotorGap = Region[{r['rotor_gap']}]; RotorAir = Region[{r['rotor_air']}];")
    w(f"  StatorFe = Region[{r['stator_fe']}]; StatorGap = Region[{r['stator_gap']}];")
    w(f"  SlotAir = Region[{r['slot_air']}]; Outer = Region[{r['outer']}];")
    for k, tag in enumerate(magnets):
        w(f"  Magnet_{k} = Region[{tag}];")
    for k, tag in enumerate(coils):
        w(f"  Coil_{k} = Region[{tag}];")
    w(f"  Magnets = Region[{{{', '.join(map(str, magnets))}}}];")
    w(f"  Coils = Region[{{{', '.join(map(str, coils))}}}];")
    w("  Iron = Region[{RotorFe, StatorFe}];")
    w("  Air = Region[{Shaft, RotorGap, RotorAir, StatorGap, SlotAir}];")
    w("  Airgap = Region[{RotorGap, StatorGap}];")
    w("  Linear = Region[{Air, Coils, Magnets}];")
    w("  Domain = Region[{Air, Coils, Magnets, Iron}];")
    w("}")
    w("Function {")
    w(f"  mu0 = {MU0};")
    w(f"  L = {p['length'] * mm!r};")
    w(f"  Rro = {p['r_ro'] * mm!r}; Rsi = {p['r_si'] * mm!r};")
    w("  nu[Air] = 1/mu0; nu[Coils] = 1/mu0;")
    w(f"  nu[Magnets] = 1/(mu0*{p['mur_m']!r});")
    if nonlinear is None:
        w(f"  nu[Iron] = 1/(mu0*{p['mur_fe']!r});")
        w("  dhdb[Iron] = TensorDiag[0, 0, 0];")
        w("  wco[Iron] = 0.5 * nu[] * SquNorm[$1];")
    else:
        w(_iron(nonlinear))
    # Linear media: co-energy density 1/2 nu b^2; a magnet's remanence only
    # adds a constant that moves with the rotor, so it drops out of dW'/dtheta.
    w("  wco[Linear] = 0.5 * nu[] * SquNorm[$1];")
    w("  R[] = Sqrt[X[]^2 + Y[]^2];")
    for k in range(poles):
        sign = 1 if k % 2 == 0 else -1
        w(f"  br[Magnet_{k}] = {sign * p['br']!r} * Vector[X[]/R[], Y[]/R[], 0];")
    current = {"A": "IA", "B": "IB", "C": "IC"}
    for k, (phase, sign) in enumerate(table):
        density = f"{sign} * {p['turns']!r} * {current[phase]} / {p['coil_area_mm2'] * mm * mm!r}"
        w(f"  js[Coil_{k}] = Vector[0, 0, {density}];")
    w("}")
    w("Constraint { { Name A; Case { { Region Outer; Value 0.; } } } }")
    w(
        "FunctionSpace { { Name Hcurl_a; Type Form1P;"
        " BasisFunction { { Name se; NameOfCoef ae; Function BF_PerpendicularEdge;"
        " Support Domain; Entity NodesOf[All]; } }"
        " Constraint { { NameOfCoef ae; EntityType NodesOf; NameOfConstraint A; } } } }"
    )
    w("Jacobian { { Name Vol; Case { { Region All; Jacobian Vol; } } } }")
    w(
        "Integration { { Name I1; Case { { Type Gauss; Case {"
        " { GeoElement Triangle; NumberOfPoints 3; }"
        " { GeoElement Line; NumberOfPoints 2; } } } } } }"
    )
    w("Formulation { { Name MagSta; Type FemEquation;")
    w("  Quantity { { Name a; Type Local; NameOfSpace Hcurl_a; } }")
    w("  Equation {")
    w(
        "    Galerkin { [ nu[{d a}] * Dof{d a}, {d a} ]; In Domain; Jacobian Vol; Integration I1; }"
    )
    if nonlinear is not None:
        w(
            "    Galerkin { JacNL[ dhdb[{d a}] * Dof{d a}, {d a} ]; In Iron;"
            " Jacobian Vol; Integration I1; }"
        )
    w(
        "    Galerkin { [ -nu[] * br[], {d a} ]; In Magnets; Jacobian Vol; Integration I1; }"
    )
    w("    Galerkin { [ -js[], {a} ]; In Coils; Jacobian Vol; Integration I1; }")
    w("  } } }")
    w("Resolution { { Name MagSta; System { { Name S; NameOfFormulation MagSta; } }")
    if nonlinear is None:
        w("  Operation { Generate[S]; Solve[S]; SaveSolution[S]; } } }")
    else:
        # Damped Newton to a loose tolerance, then full Newton. Undamped
        # Newton (and fixed-point iteration) cycles from a cold start on
        # this machine at rated current, as the benchmark's own model does;
        # damping 0.5 reaches 1e-3 in 10-13 iterations, and full Newton then
        # converges quadratically in 3-4 (rung M2).
        w(
            f"  Operation {{ IterativeLoop[{DAMPED_MAX}, {DAMPED_TOL}, {DAMPING}] {{"
            " GenerateJac[S]; SolveJac[S]; }"
            f" IterativeLoop[{NEWTON_MAX}, {NEWTON_TOL}, 1] {{"
            " GenerateJac[S]; SolveJac[S]; } SaveSolution[S]; } } }"
        )
    w("PostProcessing { { Name MagSta; NameOfFormulation MagSta; Quantity {")
    w(
        "  { Name torque; Value { Integral { [ L/(mu0*(Rsi - Rro))"
        " * (CompX[{d a}]*X[] + CompY[{d a}]*Y[])"
        " * (CompY[{d a}]*X[] - CompX[{d a}]*Y[]) / R[] ];"
        " In Airgap; Jacobian Vol; Integration I1; } } }"
    )
    w(
        "  { Name coenergy; Value { Integral { [ L * wco[{d a}] ];"
        " In Domain; Jacobian Vol; Integration I1; } } }"
    )
    for k in range(slots):
        w(
            f"  {{ Name a_{k}; Value {{ Integral {{ [ CompZ[{{a}}] ];"
            f" In Coil_{k}; Jacobian Vol; Integration I1; }} }} }}"
        )
    w("} } }")
    w("PostOperation { { Name MagSta; NameOfPostProcessing MagSta; Operation {")
    out = 'StrCat["res/{q}_", Sprintf["%g", STEP], ".txt"]'
    w(
        f"  Print[ torque[Airgap], OnGlobal, Format Table, File {out.format(q='torque')} ];"
    )
    w(
        f"  Print[ coenergy[Domain], OnGlobal, Format Table,"
        f" File {out.format(q='coenergy')} ];"
    )
    for k in range(slots):
        w(
            f"  Print[ a_{k}[Coil_{k}], OnGlobal, Format Table,"
            f" File > {out.format(q='coil_a')} ];"
        )
    w("} } }")
    return "\n".join(lines) + "\n"


#: The DEVELOPMENT iron: Brauer's form nu(b^2) = k1 + k2 exp(k3 b^2) (nu in
#: m/H), with the coefficients the ONELAB electric-machine models use for
#: their analytical law (100, 10, 1.8). A generic soft iron, not a named
#: commercial steel: relative permeability about 7,900 at low field, 230 at
#: 1.8 T and 60 at 2 T. The reference is graded against this declared law.
BRAUER = (100.0, 10.0, 1.8)


def _iron(law):
    """The iron law in GetDP, made physical at high field.

    Brauer's exponential alone grows without bound: past about 2.5 T it makes
    iron less permeable than vacuum (at 3 T, mu_r about 0.007), and a Newton
    iterate passing there goes to NaN (rung M2). A hard cap at 1/mu0 removes
    that but leaves a kink that Newton cycles on. So vacuum permeability is
    added in parallel, mu = mu_brauer + mu0 (B = mu0 H + M, M saturating):
        nu(s) = nu_b(s) / (1 + mu0 nu_b(s)),  nu_b = k1 + k2 exp(k3 s),  s = b^2.
    Below saturation it is Brauer's law to within mu0 nu_b (about 1.4e-4 at
    low field); above, it tends smoothly to 1/mu0. Its energy density has a
    closed form: with a = 1 + mu0 k1, c = mu0 k2,
        w(s) = 1/2 [ (k1/a) s + (k2 - k1 c/a)/(c k3) ln((a + c e^{k3 s})/(a + c)) ].
    """
    k1, k2, k3 = law
    a = 1 + 4e-7 * math.pi * k1
    c = 4e-7 * math.pi * k2
    s = "SquNorm[$1]"
    # Exp's argument is bounded so no iterate overflows; at that bound the
    # law is already within 1e-300 of 1/mu0.
    e = f"Exp[Min[{k3!r} * {s}, 700]]"
    nu_b = f"({k1!r} + {k2!r} * {e})"
    coefficient = (k2 - k1 * c / a) / (c * k3)
    return "\n".join(
        [
            f"  nu[Iron] = {nu_b} / (1 + mu0 * {nu_b});",
            # dH/dB = nu I + 2 dnu/ds b (x) b; GetDP takes the second part.
            (
                f"  dhdb[Iron] = 2 * {k2 * k3!r} * {e} / (1 + mu0 * {nu_b})^2"
                " * SquDyadicProduct[$1];"
            ),
            (
                f"  wco[Iron] = nu[$1] * {s} - 0.5 * ({k1 / a!r} * {s}"
                f" + {coefficient!r} * Log[({a!r} + {c!r} * {e}) / {a + c!r}]);"
            ),
        ]
    )
