"""Closed B-E1 fixture reproducibility vocabularies."""

from __future__ import annotations

from enum import Enum


class ReproducibilityRefKind(str, Enum):
    CANDIDATE_ARTIFACT = "CANDIDATE_ARTIFACT"
    GENERATOR = "GENERATOR"
    SCORING = "SCORING"
    BACKEND_PROFILE = "BACKEND_PROFILE"
    ENVIRONMENT = "ENVIRONMENT"
    EXECUTION_LIMITS = "EXECUTION_LIMITS"
    SEED_ROLE_STRUCTURE = "SEED_ROLE_STRUCTURE"
    RECEIPT_CONSTRUCTION = "RECEIPT_CONSTRUCTION"
    HARDWARE_ROLE = "HARDWARE_ROLE"
    RECONSTRUCTION = "RECONSTRUCTION"
    REFERENCE_REALIZATION = "REFERENCE_REALIZATION"
    RANDOMNESS_ROLE = "RANDOMNESS_ROLE"
    TRAINING_SEED_ROLE = "TRAINING_SEED_ROLE"
    REPRESENTATION = "REPRESENTATION"
    EXECUTION = "EXECUTION"
    PROVENANCE = "PROVENANCE"
    SHARED_DEPENDENCY = "SHARED_DEPENDENCY"
    PROCEDURE = "PROCEDURE"
    TOLERANCE_POLICY = "TOLERANCE_POLICY"
    APPLICABILITY_RESULT = "APPLICABILITY_RESULT"
    COVERAGE_QUALIFICATION = "COVERAGE_QUALIFICATION"
    POWER_QUALIFICATION = "POWER_QUALIFICATION"
    STOPPING_QUALIFICATION = "STOPPING_QUALIFICATION"
    EVIDENCE = "EVIDENCE"
    NUMERICAL_OUTPUT = "NUMERICAL_OUTPUT"
    REASON = "REASON"
    VERIFICATION_ANCHOR = "VERIFICATION_ANCHOR"


class BackendProfileSupport(str, Enum):
    SUPPORTED = "SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    UNRESOLVED = "UNRESOLVED"


class R0Outcome(str, Enum):
    EXACT_MATCH = "EXACT_MATCH"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"


class R1Outcome(str, Enum):
    REPRODUCIBLE = "REPRODUCIBLE"
    NOT_REPRODUCIBLE = "NOT_REPRODUCIBLE"
    INDETERMINATE = "INDETERMINATE"
    R0_IDENTITY_MISMATCH = "R0_IDENTITY_MISMATCH"
    BACKEND_UNSUPPORTED = "BACKEND_UNSUPPORTED"
    INFRASTRUCTURE_FAILED = "INFRASTRUCTURE_FAILED"


class ComparisonArm(str, Enum):
    INCUMBENT = "INCUMBENT"
    CHALLENGER = "CHALLENGER"


class ProducerRole(str, Enum):
    PRODUCER_INDEPENDENT = "PRODUCER_INDEPENDENT"


class EvidenceCellState(str, Enum):
    OBSERVED = "OBSERVED"
    MISSING = "MISSING"
    CENSORED = "CENSORED"
    RECONSTRUCTION_FAILED = "RECONSTRUCTION_FAILED"
    MEASUREMENT_UNRESOLVED = "MEASUREMENT_UNRESOLVED"
    INFRASTRUCTURE_FAILED = "INFRASTRUCTURE_FAILED"


class EvidenceFactorKind(str, Enum):
    REFERENCE_VARIABILITY = "REFERENCE_VARIABILITY"
    PRIMARY_WITNESS_DISAGREEMENT = "PRIMARY_WITNESS_DISAGREEMENT"
    MEASUREMENT_REFERENCE_FLOOR = "MEASUREMENT_REFERENCE_FLOOR"
    GENERATOR_REFERENCE_DISCREPANCY = "GENERATOR_REFERENCE_DISCREPANCY"
    RECONSTRUCTION_VARIABILITY = "RECONSTRUCTION_VARIABILITY"
    FINITE_CASE_TRAJECTORY_SAMPLING = "FINITE_CASE_TRAJECTORY_SAMPLING"


class EvidenceFactorState(str, Enum):
    OBSERVED = "OBSERVED"
    UNRESOLVED = "UNRESOLVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    FAILED = "FAILED"


class SharedDependencyKind(str, Enum):
    COMMON_CASE = "COMMON_CASE"
    COMMON_RANDOM_NUMBERS = "COMMON_RANDOM_NUMBERS"
    JOINT_REFERENCE_REALIZATION = "JOINT_REFERENCE_REALIZATION"
    PAIRED_TRAINING_SEED = "PAIRED_TRAINING_SEED"
    HARDWARE_ROLE = "HARDWARE_ROLE"
    REPRESENTATION = "REPRESENTATION"
    EXECUTION = "EXECUTION"
    DATA = "DATA"
    BACKBONE = "BACKBONE"
    IMPLEMENTATION = "IMPLEMENTATION"


class DependencyRelation(str, Enum):
    SHARED = "SHARED"
    DELIBERATELY_PAIRED = "DELIBERATELY_PAIRED"
    DISTINCT = "DISTINCT"


class UnresolvedClaimKind(str, Enum):
    POPULATION_ADEQUACY = "POPULATION_ADEQUACY"
    MEASUREMENT_ADEQUACY = "MEASUREMENT_ADEQUACY"
    MODEL_FORM_ADEQUACY = "MODEL_FORM_ADEQUACY"


class ProcedureKind(str, Enum):
    JOINT_PROPAGATION = "JOINT_PROPAGATION"
    CONSERVATIVE_BOUND = "CONSERVATIVE_BOUND"
    QUALIFIED_QUADRATURE = "QUALIFIED_QUADRATURE"
    QUALIFIED_INDEPENDENCE = "QUALIFIED_INDEPENDENCE"
    QUALIFIED_ZERO_COVARIANCE = "QUALIFIED_ZERO_COVARIANCE"


class ApplicabilityStatus(str, Enum):
    APPLICABLE = "APPLICABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNRESOLVED = "UNRESOLVED"
    EVIDENCE_MISMATCH = "EVIDENCE_MISMATCH"


class DecisionStability(str, Enum):
    STABLE = "STABLE"
    UNSTABLE = "UNSTABLE"
    INDETERMINATE = "INDETERMINATE"


class ScientificOutcome(str, Enum):
    RESOLVED = "RESOLVED"
    RESOLVED_SUPERIOR = "RESOLVED_SUPERIOR"
    RESOLVED_NOT_SUPERIOR = "RESOLVED_NOT_SUPERIOR"
    UNRESOLVED_INDETERMINATE = "UNRESOLVED_INDETERMINATE"
    EVIDENCE_DEFERRED = "EVIDENCE_DEFERRED"
    REFERENCE_UNCERTAIN = "REFERENCE_UNCERTAIN"
    REFERENCE_DISAGREEMENT = "REFERENCE_DISAGREEMENT"
    REFERENCE_NOT_APPLICABLE = "REFERENCE_NOT_APPLICABLE"
    REFERENCE_FAILED = "REFERENCE_FAILED"
    RECONSTRUCTION_FAILED = "RECONSTRUCTION_FAILED"
    MEASUREMENT_UNRESOLVED = "MEASUREMENT_UNRESOLVED"
    INFRASTRUCTURE_FAILED = "INFRASTRUCTURE_FAILED"


class ReconstructionAuditStage(str, Enum):
    STATIC_ADMISSION = "STATIC_ADMISSION"
    COMPLETE_BASE = "COMPLETE_BASE"
    FROZEN_BUILD_REUSE = "FROZEN_BUILD_REUSE"
    REPEAT_PROMOTION = "REPEAT_PROMOTION"
    RANDOM_STABILITY_AUDIT = "RANDOM_STABILITY_AUDIT"
    SCIENTIFIC_SEQUENTIAL = "SCIENTIFIC_SEQUENTIAL"
    HEURISTIC_FUTILITY = "HEURISTIC_FUTILITY"


class AuditStageState(str, Enum):
    SATISFIED = "SATISFIED"
    PENDING = "PENDING"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    STOP_REQUESTED = "STOP_REQUESTED"


class ScientificSequentialAction(str, Enum):
    CONTINUE_EXTENSION = "CONTINUE_EXTENSION"
    STOP_RESOLVED = "STOP_RESOLVED"
    EXHAUSTED_INDETERMINATE = "EXHAUSTED_INDETERMINATE"


REQUIRED_EVIDENCE_FACTORS = tuple(EvidenceFactorKind)
