#!/usr/bin/env bash
# Disposable C0 integration. No public RPC, valuable network or treasury.
set -euo pipefail
cd "$(dirname "$0")/../.."
mode="${CARBON_LOCALNET_MODE:-full}"
profile="${CARBON_LOCALNET_PROFILE:-fast}"
keep="${CARBON_LOCALNET_KEEP:-0}"
[[ "$mode" == inspect || "$mode" == diagnostic || "$mode" == full || "$mode" == operator ]] || { echo 'Unknown localnet mode.' >&2; exit 2; }
[[ "$profile" == fast || "$profile" == standard ]] || { echo 'Unknown localnet profile.' >&2; exit 2; }
[[ "$mode" != diagnostic || "$profile" == standard ]] || { echo 'Registration diagnostic requires the standard profile.' >&2; exit 2; }
[[ "$mode" != operator || "$profile" == fast ]] || { echo 'Operator evidence remains bound to the fast profile.' >&2; exit 2; }
[[ "$keep" == 0 || "$keep" == 1 ]] || { echo 'KEEP must be 0 or 1.' >&2; exit 2; }
evidence="${1:-.carbon-artifacts/localnet}"
mkdir -p "$evidence"
evidence="$(cd "$evidence" && pwd)"
export CARBON_LOCALNET_EVIDENCE="$evidence"
[[ "$(uname -s)" == Linux && "$(uname -m)" == x86_64 ]] || {
  echo 'Requires linux/amd64 with Docker and the locked Carbon development environment.' >&2
  exit 2
}
./scripts/dev/doctor.sh
docker info >/dev/null
image="$(.venv/bin/python -c 'import json; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["image"]+"@"+p["image_digest"])')"
name="carbon-localnet-${GITHUB_RUN_ID:-local}-$$"
network="$name-network"
export CARBON_LOCALNET_STATE="${CARBON_LOCALNET_STATE:-$PWD/.local/private-$name}"
export CARBON_LOCALNET_MODE="$mode" CARBON_LOCALNET_PROFILE="$profile"
cleanup() {
  # Only networking/configuration generated by this disposable harness; no environment/keys.
  docker inspect --format '{{json .NetworkSettings}}' "$name" >"$evidence/docker-network.json" 2>/dev/null || true
  docker inspect --format '{{json .HostConfig.PortBindings}}' "$name" >"$evidence/docker-requested-ports.json" 2>/dev/null || true
  docker inspect --format '{{json .HostConfig}}' "$name" >"$evidence/docker-host-config.json" 2>/dev/null || true
  docker stats --no-stream --format '{{json .}}' "$name" >"$evidence/docker-resource-usage.json" 2>/dev/null || true
  docker version --format '{{json .Server}}' >"$evidence/docker-version.json" 2>/dev/null || true
  docker logs "$name" >"$evidence/node.log" 2>&1 || true
  if [[ "$keep" == 1 ]]; then
    echo "Retained disposable container: $name; network: $network; private state: $CARBON_LOCALNET_STATE"
    return
  fi
  docker stop --time 35 "$name" >/dev/null 2>&1 || true
  docker rm "$name" >/dev/null 2>&1 || true
  docker network rm "$network" >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM
docker pull --platform linux/amd64 "$image"
export CARBON_LOCALNET_IMAGE="$image"
# This no-network filesystem check must pass before the disposable network or
# any node/application key is created. Inspect mode may discover identities;
# all signing modes require those identities to already be bound.
.venv/bin/python -m carbon.chain.localnet inspect-image
docker network create --internal --label carbon.scope=disposable-localnet "$network" >/dev/null
startup="$(.venv/bin/python -c 'import os; from carbon.chain.localnet import startup_for; print(startup_for(os.environ["CARBON_LOCALNET_PROFILE"]), end="")')"
memory="$(.venv/bin/python -c 'import json, os; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["budgets"][os.environ["CARBON_LOCALNET_MODE"]]["memory"], end="")')"
cpus="$(.venv/bin/python -c 'import json, os; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["budgets"][os.environ["CARBON_LOCALNET_MODE"]]["cpus"], end="")')"
pids="$(.venv/bin/python -c 'import json, os; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["budgets"][os.environ["CARBON_LOCALNET_MODE"]]["pids_limit"], end="")')"
wall="$(.venv/bin/python -c 'import json, os; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["budgets"][os.environ["CARBON_LOCALNET_MODE"]]["wall_seconds"], end="")')"
docker run --detach --entrypoint /bin/bash --name "$name" --platform linux/amd64 --network "$network" \
  --label carbon.scope=disposable-localnet --label "carbon.runtime-profile=$profile" \
  --label "carbon.execution-mode=$mode" --memory "$memory" --cpus "$cpus" --pids-limit "$pids" \
  "$image" -c "$startup" >"$evidence/container-id.txt"
export CARBON_LOCALNET_CONTAINER="$name"
# Process-owned loopback relays reach only the inspected internal container RPC.
# Probe validates isolation and genesis before constructing any key.
timeout --signal=TERM --kill-after=30 "$wall" .venv/bin/python -m carbon.chain.localnet run
