#!/usr/bin/env bash
# Disposable C0 integration. No public RPC, valuable network or treasury.
set -euo pipefail
cd "$(dirname "$0")/../.."
mode="${CARBON_LOCALNET_MODE:-full}"
keep="${CARBON_LOCALNET_KEEP:-0}"
[[ "$mode" == full || "$mode" == operator ]] || { echo 'Unknown localnet mode.' >&2; exit 2; }
[[ "$keep" == 0 || "$keep" == 1 ]] || { echo 'KEEP must be 0 or 1.' >&2; exit 2; }
evidence="${1:-.carbon-artifacts/localnet}"
mkdir -p "$evidence"
evidence="$(cd "$evidence" && pwd)"
[[ "$(uname -s)" == Linux && "$(uname -m)" == x86_64 ]] || {
  echo 'Requires linux/amd64 with Docker and the locked Carbon development environment.' >&2
  exit 2
}
./scripts/dev/doctor.sh
docker info >/dev/null
image="$(.venv/bin/python -c 'import json; p=json.load(open("scripts/dev/localnet-runtime.json")); print(p["image"]+"@"+p["image_digest"])')"
name="carbon-localnet-${GITHUB_RUN_ID:-local}-$$"
network="$name-network"
export CARBON_LOCALNET_STATE="${CARBON_LOCALNET_STATE:-$PWD/.local/private-$name}"
export CARBON_LOCALNET_MODE="$mode"
cleanup() {
  # Only networking/configuration generated by this disposable harness; no environment/keys.
  docker inspect --format '{{json .NetworkSettings}}' "$name" >"$evidence/docker-network.json" 2>/dev/null || true
  docker inspect --format '{{json .HostConfig.PortBindings}}' "$name" >"$evidence/docker-requested-ports.json" 2>/dev/null || true
  docker version --format '{{json .Server}}' >"$evidence/docker-version.json" 2>/dev/null || true
  docker logs "$name" >"$evidence/node.log" 2>&1 || true
  if [[ "$keep" == 1 ]]; then
    echo "Retained disposable container: $name; network: $network; private state: $CARBON_LOCALNET_STATE"
    return
  fi
  docker stop --time 35 "$name" >/dev/null 2>&1 || true
  docker rm "$name" >/dev/null 2>&1 || true
  docker network rm "$network" >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM
docker pull --platform linux/amd64 "$image"
docker network create --internal --label carbon.scope=disposable-localnet "$network" >/dev/null
startup="$(.venv/bin/python -c 'from carbon.chain.localnet import STARTUP; print(STARTUP, end="")')"
docker run --detach --entrypoint /bin/bash --name "$name" --platform linux/amd64 --network "$network" \
  --label carbon.scope=disposable-localnet --memory 5g --cpus 3 \
  "$image" -c "$startup" >"$evidence/container-id.txt"
export CARBON_LOCALNET_CONTAINER="$name" CARBON_LOCALNET_EVIDENCE="$evidence"
# Process-owned loopback relays reach only the inspected internal container RPC.
# Probe validates isolation and genesis before constructing any key.
.venv/bin/python -m carbon.chain.localnet run
