/* Carbon Opportunity Workbench. Pure planning arithmetic, never official scoring. */
(function (root) {
'use strict';
const VERSION='carbon_workbench_draft_v0.2';
const WORKSPACE_VERSION='carbon_workbench_workspace_v0.2';
const APP_VERSION='Carbon Opportunity Workbench v0.2';
const LEGACY_DRAFT_VERSION='carbon_workbench_draft_v0.1';
const LEGACY_WORKSPACE_VERSION='carbon_workbench_workspace_v0.1';
const CHECKS=['job_access','reference','reconstruction','exam','deployment','value'];
const STATES=['UNKNOWN','SUPPORTED_FOR_STAGE','BLOCKED_FOR_SCOPE'];
const PLANNING=['UNREVIEWED','INVESTIGATE','PILOT_PROPOSAL','PARTNER_DEPENDENT','PARKED','DECLINE_CURRENT_SCOPE'];
const INPUTS=['hardware','daily_pool_hours','supply_per_day','repetitions','train_ref_lo','train_ref_hi','rebuild_lo','rebuild_hi','eval_lo','eval_hi','overhead_lo','overhead_hi','promotion_lo','promotion_hi','ref_lo','ref_hi','cohort','qualification_cost','qualification_currency','qualification_days','qualification_risk','baseline_latency_ms','required_latency_ms'];
const ROLES=['verification','training_data','routine_exam','independent_witness','physical_anchor','protected_audit'];
const BRIEF=['job','output','context','baseline','reference_access','accuracy','latency','volume','budget','timing','privacy','contact','notes'];
const CONTROL_IDS=['P1','P2','P3','P4','P5','P6','P7','P8'];
const CONTROL_STATES=['UNASSESSED','EVIDENCE_ASSEMBLED','BLOCKED'];
const BLOCKER_IDS=['AT-09','AT-16','AT-19','AT-22','AT-30'];
const APPLICABILITY=['UNKNOWN','APPLICABLE','NOT_APPLICABLE_ASSERTED'];
const QUANTITY_STATUS=['unknown','observed','source_estimated','user_assumed','simulated'];
const ECON_UNITS=['','synthetic work units','CPU seconds — same profile','GPU seconds — same profile','explicit currency rate/basis','other named matched unit'];
const ECON_FIELDS=['reference_work','group_overhead','group_size','unit','unit_scope','reference_status','overhead_status','group_size_status','compatible_demand_status','compatible_demand_source','field_dependent','completed_comparisons','offered_requests','unresolved_or_censored','upfront_cost','upfront_duration','upfront_risk'];
const GAP_IDS=['compatibility_identity','compatible_dispatch_demand','same_identity_reference_cost','variant_b_overhead','field_evidence_adequacy','service_envelope'];
const GAP_FIELDS=['source_reference','reviewer_notes','measurement_method','unresolved_assumptions','source_owner','smallest_observation','why_decision_changes'];
const AUTHORITY={evidence_status:'USER_ENTERED_UNREVIEWED',qualification_status:'NOT_QUALIFIED_BY_THIS_TOOL',submission_status:'NOT_SENT',reuse_permission:'NOT_GRANTED'};
const text=(v,max=8000)=>typeof v==='string' && v.length<=max;
const cleanCopy=v=>JSON.parse(JSON.stringify(v));

function number(v,name,{positive=false,integer=false}={}) {
 if(v===undefined || v===null || v==='') throw Error(name+': missing');
 if(typeof v==='boolean' || (typeof v!=='number' && typeof v!=='string')) throw Error(name+': invalid type');
 if(typeof v==='string' && !/^\d+(\.\d+)?$/.test(v)) throw Error(name+': use a non-negative decimal');
 const n=Number(v);
 if(!Number.isFinite(n)||n<0||(positive&&n<=0)||(integer&&!Number.isSafeInteger(n))||n>Number.MAX_SAFE_INTEGER) throw Error(name+': invalid value');
 return n;
}
function interval(p,prefix){
 const lo=number(p[prefix+'_lo'],prefix+' lower');const hi=number(p[prefix+'_hi'],prefix+' upper');
 if(lo>hi)throw Error(prefix+': lower exceeds upper');return [lo,hi];
}
function maxCompleted(budget,per,ref,cohort){
 if(per<=0)throw Error('Per-candidate work must be positive');
 let low=0,high=Math.floor(budget/per);
 if(!Number.isSafeInteger(high)||high>1e9)throw Error('Capacity exceeds prototype arithmetic bounds');
 while(low<high){const mid=Math.floor((low+high+1)/2);if(mid*per+Math.ceil(mid/cohort)*ref<=budget)low=mid;else high=mid-1;}
 return low;
}
function profile(p){
 try{
  if(!text(p.hardware,300)||!p.hardware.trim())throw Error('Describe the homogeneous compute pool first');
  const hours=number(p.daily_pool_hours,'Matched worker-hours/day',{positive:true});
  const reps=number(p.repetitions,'Reconstruction repetitions',{positive:true,integer:true});
  const b=number(p.cohort,'Committed candidates/cohort',{positive:true,integer:true});
  if(reps>1000||b>10000)throw Error('Prototype repetition/cohort limit exceeded');
  const train=interval(p,'train_ref'),rebuild=interval(p,'rebuild'),ev=interval(p,'eval'),ov=interval(p,'overhead'),pr=interval(p,'promotion'),ref=interval(p,'ref');
  const c=[0,1].map(i=>reps*(train[i]+rebuild[i])+ev[i]+ov[i]+pr[i]);
  if(!c.every(x=>Number.isFinite(x)&&x>0)||!Number.isFinite(hours*3600))throw Error('Finite positive total work is required');
  let lo=maxCompleted(hours*3600,c[1],ref[1],b),hi=maxCompleted(hours*3600,c[0],ref[0],b);
  let supply=null;
  if(p.supply_per_day!==''&&p.supply_per_day!==null&&p.supply_per_day!==undefined){supply=number(p.supply_per_day,'Distinct proposals/day',{integer:true});lo=Math.min(lo,supply);hi=Math.min(hi,supply);}
  return {status:'SCENARIO_ONLY',validator_count:1,capacity_lower:lo,capacity_upper:hi,per_candidate_seconds:c,full_cohort_seconds:[b*c[0]+ref[0],b*c[1]+ref[1]],reference_shared:b>1,supply_known:supply!==null,note:'Legacy hypothetical sharing-capacity calculation. It is not the Variant A baseline, measured throughput, demand-qualified sharing, or runtime permission.'};
 }catch(e){return {status:'INPUT_REQUIRED_OR_INVALID',reason:e.message};}
}
function margin(value,limit,operator='<=' ){
 const x=number(value,'Observation');const l=number(limit,'Requirement',{positive:true});
 if(!['<','<='].includes(operator))throw Error('Unsupported comparator');
 return {headroom:1-x/l,within:operator==='<'?x<l:x<=l};
}

function emptyReviewFields(){return {source_reference:'',reviewer_notes:'',measurement_method:'',unresolved_assumptions:''};}
function emptyGap(){return {...emptyReviewFields(),source_owner:'',smallest_observation:'',why_decision_changes:''};}
function newDraft(id,sourceSha){
 const inputs=Object.fromEntries(INPUTS.map(k=>[k,'']));
 const controls=Object.fromEntries(CONTROL_IDS.map(k=>[k,{state:'UNASSESSED',...emptyReviewFields()}]));
 const blockers=Object.fromEntries(BLOCKER_IDS.map(k=>[k,{applicability:'UNKNOWN',...emptyReviewFields()}]));
 const economics=Object.fromEntries(ECON_FIELDS.map(k=>[k,'']));
 economics.reference_status='unknown';economics.overhead_status='unknown';economics.group_size_status='unknown';economics.compatible_demand_status='unknown';economics.field_dependent='UNKNOWN';
 return {schema_version:VERSION,opportunity_id:id,source_sha256:sourceSha,planning_state:'UNREVIEWED',fit_checks:Object.fromEntries(CHECKS.map(k=>[k,{state:'UNKNOWN',evidence_note:''}])),inputs,brief:Object.fromEntries(BRIEF.map(k=>[k,''])),reference_roles:[],reference_architecture:Object.fromEntries(ROLES.map(k=>[k,{family:'',implementation_scope:'',evidence_note:''}])),next_test:'',study_refs:[],review_note:'',protection:{controls,blockers,publication_review:{desired_future_feature:true,rights_notes:'',retirement_notes:'',status:'DEFERRED_NOT_IMPLEMENTED'}},reference_economics:economics,dynamic_scenario:{scenario:'slow_or_unresolved_member',overhead:'4'},next_evidence:Object.fromEntries(GAP_IDS.map(k=>[k,emptyGap()])),legacy_sharing_scenario:null,migration_receipt:null,...AUTHORITY};
}
function keysExact(o,keys,name){if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).sort().join('|')!==[...keys].sort().join('|'))throw Error(name+': unexpected fields');}
function validateTextObject(o,keys,name,max=8000){keysExact(o,keys,name);for(const k of keys)if(!text(o[k],max))throw Error(name+': invalid '+k);}
function validateDraft(d,ids,sourceSha){
 const template=newDraft('',sourceSha);keysExact(d,Object.keys(template),'Draft');
 if(d.schema_version!==VERSION||!ids.includes(d.opportunity_id)||d.source_sha256!==sourceSha)throw Error('Draft source, identity, or schema mismatch');
 for(const [f,v] of Object.entries(AUTHORITY))if(d[f]!==v)throw Error('Imported state cannot grant evidence, qualification, submission, or reuse authority');
 if(!PLANNING.includes(d.planning_state))throw Error('Unknown planning state');
 keysExact(d.fit_checks,CHECKS,'Fit checks');for(const c of CHECKS){keysExact(d.fit_checks[c],['state','evidence_note'],'Check');if(!STATES.includes(d.fit_checks[c].state)||!text(d.fit_checks[c].evidence_note))throw Error('Invalid check');}
 validateTextObject(d.inputs,INPUTS,'Inputs',300);validateTextObject(d.brief,BRIEF,'Brief');
 keysExact(d.reference_architecture,ROLES,'Reference architecture');for(const role of ROLES)validateTextObject(d.reference_architecture[role],['family','implementation_scope','evidence_note'],'Reference role');
 if(!Array.isArray(d.reference_roles)||d.reference_roles.length>6||new Set(d.reference_roles).size!==d.reference_roles.length||!d.reference_roles.every(x=>ROLES.includes(x)))throw Error('Invalid reference roles');
 if(!Array.isArray(d.study_refs)||d.study_refs.length>100||!d.study_refs.every(x=>text(x,200)))throw Error('Invalid study references');if(!text(d.next_test)||!text(d.review_note))throw Error('Invalid review notes');
 keysExact(d.protection,['controls','blockers','publication_review'],'Protection');keysExact(d.protection.controls,CONTROL_IDS,'Protection controls');
 for(const id of CONTROL_IDS){const c=d.protection.controls[id];keysExact(c,['state',...Object.keys(emptyReviewFields())],'Protection control');if(!CONTROL_STATES.includes(c.state))throw Error('Invalid protection control state');for(const k of Object.keys(emptyReviewFields()))if(!text(c[k]))throw Error('Invalid protection control text');}
 keysExact(d.protection.blockers,BLOCKER_IDS,'Protection blockers');for(const id of BLOCKER_IDS){const b=d.protection.blockers[id];keysExact(b,['applicability',...Object.keys(emptyReviewFields())],'Protection blocker');if(!APPLICABILITY.includes(b.applicability))throw Error('Invalid blocker applicability');for(const k of Object.keys(emptyReviewFields()))if(!text(b[k]))throw Error('Invalid blocker text');}
 keysExact(d.protection.publication_review,['desired_future_feature','rights_notes','retirement_notes','status'],'Publication review');if(d.protection.publication_review.desired_future_feature!==true||d.protection.publication_review.status!=='DEFERRED_NOT_IMPLEMENTED'||!text(d.protection.publication_review.rights_notes)||!text(d.protection.publication_review.retirement_notes))throw Error('Invalid publication review');
 validateTextObject(d.reference_economics,ECON_FIELDS,'Reference economics',300);for(const k of ['reference_status','overhead_status','group_size_status','compatible_demand_status'])if(!QUANTITY_STATUS.includes(d.reference_economics[k]))throw Error('Invalid quantity status');if(!['UNKNOWN','YES','NO'].includes(d.reference_economics.field_dependent))throw Error('Invalid field-dependence status');if(!ECON_UNITS.includes(d.reference_economics.unit))throw Error('Invalid or mismatched economics unit');
 keysExact(d.dynamic_scenario,['scenario','overhead'],'Dynamic scenario');if(!text(d.dynamic_scenario.scenario,100)||!text(d.dynamic_scenario.overhead,30))throw Error('Invalid dynamic scenario');keysExact(d.next_evidence,GAP_IDS,'Next evidence');for(const id of GAP_IDS)validateTextObject(d.next_evidence[id],GAP_FIELDS,'Evidence gap');
 if(d.legacy_sharing_scenario!==null){keysExact(d.legacy_sharing_scenario,['status','cohort','ref_lo','ref_hi','hardware','note'],'Legacy sharing scenario');validateTextObject(d.legacy_sharing_scenario,['status','cohort','ref_lo','ref_hi','hardware','note'],'Legacy sharing scenario');if(d.legacy_sharing_scenario.status!=='LEGACY_HYPOTHETICAL_SHARING_SCENARIO')throw Error('Invalid legacy status');}
 if(d.migration_receipt!==null){keysExact(d.migration_receipt,['from','to','original_sha256','digest_status','semantic_changes'],'Migration receipt');if(d.migration_receipt.from!==LEGACY_DRAFT_VERSION||d.migration_receipt.to!==VERSION||!text(d.migration_receipt.original_sha256,64)||!['VERIFIED_WEB_CRYPTO','UNAVAILABLE'].includes(d.migration_receipt.digest_status)||!Array.isArray(d.migration_receipt.semantic_changes)||!d.migration_receipt.semantic_changes.every(x=>text(x,500)))throw Error('Invalid migration receipt');}
 return cleanCopy(d);
}

function strictJsonParse(raw,{maxBytes=1000000,maxDepth=24}={}){
 if(typeof raw!=='string'||new TextEncoder().encode(raw).length>maxBytes)throw Error('Import exceeds the declared size limit');let i=0;const dangerous=new Set(['__proto__','prototype','constructor']);const ws=()=>{while(/\s/.test(raw[i]||''))i++;};const fail=m=>{throw Error('Invalid JSON: '+m+' at byte '+i);};
 function value(depth){if(depth>maxDepth)fail('nesting limit exceeded');ws();const c=raw[i];if(c==='{')return object(depth+1);if(c==='[')return array(depth+1);if(c==='"')return string();if(c==='t'&&raw.slice(i,i+4)==='true'){i+=4;return true;}if(c==='f'&&raw.slice(i,i+5)==='false'){i+=5;return false;}if(c==='n'&&raw.slice(i,i+4)==='null'){i+=4;return null;}return num();}
 function string(){const start=i++;let escaped=false;for(;i<raw.length;i++){const c=raw[i];if(!escaped&&c==='"'){i++;try{return JSON.parse(raw.slice(start,i));}catch(_){fail('invalid string');}}if(!escaped&&c==='\\')escaped=true;else{if(c.charCodeAt(0)<32)fail('control character in string');escaped=false;}}fail('unterminated string');}
 function num(){const m=raw.slice(i).match(/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/);if(!m)fail('expected value');i+=m[0].length;const n=Number(m[0]);if(!Number.isFinite(n))fail('nonfinite number');if(Number.isInteger(n)&&!Number.isSafeInteger(n))fail('unsafe integer');return n;}
 function array(depth){i++;const out=[];ws();if(raw[i]===']'){i++;return out;}while(true){out.push(value(depth));ws();if(raw[i]===']'){i++;return out;}if(raw[i++]!==',')fail('expected comma');}}
 function object(depth){i++;const out=Object.create(null),seen=new Set();ws();if(raw[i]==='}'){i++;return out;}while(true){ws();if(raw[i]!=='"')fail('expected object key');const k=string();if(seen.has(k))fail('duplicate object member '+k);if(dangerous.has(k))fail('forbidden object member '+k);seen.add(k);ws();if(raw[i++]!==':')fail('expected colon');out[k]=value(depth);ws();if(raw[i]==='}'){i++;return out;}if(raw[i++]!==',')fail('expected comma');}}
 const out=value(0);ws();if(i!==raw.length)fail('trailing content');return out;
}

function validateLegacyDraft(d,ids,sourceSha){
 const legacyKeys=['schema_version','opportunity_id','source_sha256','planning_state','fit_checks','inputs','brief','reference_roles','reference_architecture','next_test','study_refs','review_note','evidence_status','qualification_status','submission_status','reuse_permission'];keysExact(d,legacyKeys,'Legacy draft');if(d.schema_version!==LEGACY_DRAFT_VERSION||!ids.includes(d.opportunity_id)||d.source_sha256!==sourceSha)throw Error('Legacy draft source, identity, or schema mismatch');for(const [f,v] of Object.entries(AUTHORITY))if(d[f]!==v)throw Error('Legacy import cannot grant authority');if(!PLANNING.includes(d.planning_state))throw Error('Unknown legacy planning state');keysExact(d.fit_checks,CHECKS,'Legacy fit checks');for(const c of CHECKS){keysExact(d.fit_checks[c],['state','evidence_note'],'Legacy check');if(!STATES.includes(d.fit_checks[c].state)||!text(d.fit_checks[c].evidence_note))throw Error('Invalid legacy check');}validateTextObject(d.inputs,INPUTS,'Legacy inputs',300);validateTextObject(d.brief,BRIEF,'Legacy brief');keysExact(d.reference_architecture,ROLES,'Legacy reference architecture');for(const r of ROLES)validateTextObject(d.reference_architecture[r],['family','implementation_scope','evidence_note'],'Legacy reference role');if(!Array.isArray(d.reference_roles)||!d.reference_roles.every(x=>ROLES.includes(x))||!Array.isArray(d.study_refs)||!d.study_refs.every(x=>text(x,200))||!text(d.next_test)||!text(d.review_note))throw Error('Invalid legacy notes');return d;
}
function migrateLegacyDraft(old,ids,sourceSha,originalSha,digestStatus){validateLegacyDraft(old,ids,sourceSha);const d=newDraft(old.opportunity_id,sourceSha);for(const k of ['planning_state','fit_checks','inputs','brief','reference_roles','reference_architecture','next_test','study_refs','review_note'])d[k]=cleanCopy(old[k]);d.legacy_sharing_scenario={status:'LEGACY_HYPOTHETICAL_SHARING_SCENARIO',cohort:old.inputs.cohort,ref_lo:old.inputs.ref_lo,ref_hi:old.inputs.ref_hi,hardware:old.inputs.hardware,note:'Preserved v0.1 cohort/reference inputs. They do not activate Variant B or establish observed batch size; Variant A is derived separately.'};d.migration_receipt={from:LEGACY_DRAFT_VERSION,to:VERSION,original_sha256:originalSha||'',digest_status:digestStatus||'UNAVAILABLE',semantic_changes:['Protection starts UNASSESSED.','Legacy cohort/reference values remain hypothetical sharing inputs.','Variant A is the separate immutable DEVELOPMENT baseline.','Derived outputs are recomputed; imported authority states remain unavailable.']};return d;}
function validateEvidenceClaim(c){const keys=['schema_version','study_id','evidence_version','recommendation','source_reference','delivery_status','qualified_carbon_evidence','content_sha256'];keysExact(c,keys,'Imported evidence claim');if(c.schema_version!=='carbon.workbench.cpes-study-import.v1'||![c.study_id,c.evidence_version,c.recommendation,c.source_reference,c.delivery_status].every(x=>text(x,300))||c.qualified_carbon_evidence!==null||!/^[a-f0-9]{64}$/.test(c.content_sha256))throw Error('Unsupported evidence claim');return cleanCopy(c);}
function validateShortlist(v,ids){if(!Array.isArray(v)||v.length>3||new Set(v).size!==v.length||!v.every(x=>ids.includes(x)))throw Error('Invalid shortlist');}
function validateWorkspaceReceipt(r){keysExact(r,['from','to','original_sha256','digest_status','semantic_changes'],'Workspace migration receipt');if(r.from!==LEGACY_WORKSPACE_VERSION||r.to!==WORKSPACE_VERSION||!text(r.original_sha256,64)||!['VERIFIED_WEB_CRYPTO','UNAVAILABLE'].includes(r.digest_status)||!Array.isArray(r.semantic_changes)||r.semantic_changes.length>12||!r.semantic_changes.every(x=>text(x,500)))throw Error('Invalid workspace migration receipt');return cleanCopy(r);}
function readWorkspace(raw,ids,sourceSha,{originalSha='',digestStatus='UNAVAILABLE'}={}){
 const w=strictJsonParse(raw);if(w.schema_version===LEGACY_WORKSPACE_VERSION){keysExact(w,['schema_version','source_sha256','drafts','shortlist'],'Legacy workspace');if(w.source_sha256!==sourceSha||!Array.isArray(w.drafts)||w.drafts.length>64)throw Error('Legacy workspace schema/source/size mismatch');const drafts=w.drafts.map(d=>migrateLegacyDraft(d,ids,sourceSha,originalSha,digestStatus));if(new Set(drafts.map(d=>d.opportunity_id)).size!==drafts.length)throw Error('Duplicate drafts');validateShortlist(w.shortlist,ids);return {schema_version:WORKSPACE_VERSION,application_version:APP_VERSION,source_sha256:sourceSha,evidence_catalog:[],drafts,shortlist:[...w.shortlist],migration_receipts:[{from:LEGACY_WORKSPACE_VERSION,to:WORKSPACE_VERSION,original_sha256:originalSha,digest_status:digestStatus,semantic_changes:['Contained drafts migrated additively; source IDs, notes, shortlist, fit checks, references, client brief and legacy inputs preserved.']}]};}
 keysExact(w,['schema_version','application_version','source_sha256','evidence_catalog','drafts','shortlist','migration_receipts'],'Workspace');if(w.schema_version!==WORKSPACE_VERSION||w.application_version!==APP_VERSION||w.source_sha256!==sourceSha||!Array.isArray(w.drafts)||w.drafts.length>64||!Array.isArray(w.evidence_catalog)||w.evidence_catalog.length>16||!Array.isArray(w.migration_receipts)||w.migration_receipts.length>65)throw Error('Workspace schema/source/size mismatch');const drafts=w.drafts.map(d=>validateDraft(d,ids,sourceSha));if(new Set(drafts.map(d=>d.opportunity_id)).size!==drafts.length)throw Error('Duplicate drafts');validateShortlist(w.shortlist,ids);const evidence=w.evidence_catalog.map(validateEvidenceClaim);const ek=evidence.map(x=>x.study_id+'@'+x.evidence_version);if(new Set(ek).size!==ek.length)throw Error('Duplicate evidence versions');const receipts=w.migration_receipts.map(validateWorkspaceReceipt);return {...cleanCopy(w),drafts,evidence_catalog:evidence,migration_receipts:receipts};
}
function triage(d){const blocked=CHECKS.filter(k=>d.fit_checks[k].state==='BLOCKED_FOR_SCOPE');const unknown=CHECKS.filter(k=>d.fit_checks[k].state==='UNKNOWN'||(d.fit_checks[k].state==='SUPPORTED_FOR_STAGE'&&!d.fit_checks[k].evidence_note.trim()));return {status:blocked.length?'REVIEW_BLOCKERS':unknown.length?'EVIDENCE_GAPS':'REVIEW_SUPPORTING_EVIDENCE',blocked,unknown,qualification:'NOT_QUALIFIED_BY_THIS_TOOL'};}

function reviewFieldsComplete(v){return ['source_reference','reviewer_notes','measurement_method'].every(k=>v[k].trim());}
function protectionReview(d){const controls=CONTROL_IDS.map(id=>({id,state:d.protection.controls[id].state,complete:reviewFieldsComplete(d.protection.controls[id]),unresolved:!!d.protection.controls[id].unresolved_assumptions.trim(),touched:d.protection.controls[id].state!=='UNASSESSED'||Object.values(d.protection.controls[id]).some(v=>typeof v==='string'&&v.trim()&&v!=='UNASSESSED')}));const blockers=BLOCKER_IDS.map(id=>{const v=d.protection.blockers[id],complete=reviewFieldsComplete(v);return {id,applicability:v.applicability,record_complete:complete,resolved_for_scope:v.applicability==='NOT_APPLICABLE_ASSERTED'&&complete,assertion_only:v.applicability==='NOT_APPLICABLE_ASSERTED',touched:v.applicability!=='UNKNOWN'||Object.entries(v).some(([k,x])=>k!=='applicability'&&x.trim())};});const untouched=controls.every(x=>!x.touched)&&blockers.every(x=>!x.touched);const record_complete=controls.every(x=>x.state!=='UNASSESSED'&&x.complete)&&blockers.every(x=>x.record_complete);const unresolvedControls=controls.filter(x=>x.state!=='EVIDENCE_ASSEMBLED'||!x.complete||x.unresolved).map(x=>x.id);const unresolvedBlockers=blockers.filter(x=>!x.resolved_for_scope).map(x=>x.id);const state=untouched?'UNASSESSED':unresolvedControls.length||unresolvedBlockers.length?'PROTECTION_BLOCKED':record_complete?'READY_FOR_DOMAIN_REVIEW':'UNASSESSED';return {state,record_complete,unresolved_controls:unresolvedControls,unresolved_blockers:unresolvedBlockers,qualified:false,note:'Planning state only. A complete packet may retain unresolved risks; not-applicable entries are review assertions, and user notes cannot clear source-backed blockers.'};}

function fixedGroupEconomics(e){
 const out={status:'UNKNOWN',baseline:'RETAIN_A',relation:'unknown',conditional:true,unknowns:[],runtime_sharing_authorized:false};const fieldMap=[['reference_work','qualified reference work R'],['group_overhead','Variant B overhead H'],['group_size','compatible group size b'],['unit','matched unit'],['unit_scope','unit scope']];for(const [k,l] of fieldMap)if(!String(e[k]??'').trim())out.unknowns.push(l);if(e.compatible_demand_status==='unknown')out.unknowns.push('compatible demand at dispatch');if(e.field_dependent!=='NO')out.unknowns.push('field-dependent evidence requirement');if(out.unknowns.some(x=>['qualified reference work R','Variant B overhead H','compatible group size b','matched unit','unit scope'].includes(x)))return {...out,message:'Retain A. Reference cost, B overhead, group size, or compatible demand is unknown.'};
 try{const b=number(e.group_size,'Group size b',{positive:true,integer:true}),R=number(e.reference_work,'Reference work R'),H=number(e.group_overhead,'Group overhead H');if(b>10000)throw Error('Group size exceeds application bound');const a=b*R,bwork=R+H,saving=a-bwork,per=saving/b;if(![a,bwork,saving,per].every(Number.isFinite))throw Error('Economics overflow');const relation=b===1?'no_sharing_opportunity':saving>0?'favorable':saving<0?'unfavorable':'equal';const assumed=[e.reference_status,e.overhead_status,e.group_size_status].some(x=>x!=='observed')||e.compatible_demand_status!=='observed'||e.field_dependent!=='NO';let message=b===1?'Retain A. A singleton has no sharing opportunity; any unavoidable B overhead is charged.':relation==='favorable'?'Retain A. The entered B scenario saves work, but the inputs are assumptions or unqualified observations.':relation==='equal'?'Retain A. The entered scenario is break-even, not an advantage.':'Retain A. The entered B scenario uses more reference/control work.';return {...out,status:'CALCULATED_CONDITIONAL',relation,conditional:assumed,group_size:b,reference_work:R,group_overhead:H,a_reference_control_work:a,b_reference_control_work:bwork,net_saving_per_group:saving,net_saving_per_candidate:per,break_even_reference_work:b>1?H/(b-1):null,unit:e.unit,unit_scope:e.unit_scope,message,field_dependent:e.field_dependent,compatible_demand_status:e.compatible_demand_status,complete_comparisons:e.completed_comparisons===''?null:number(e.completed_comparisons,'Completed comparisons',{integer:true}),offered_requests:e.offered_requests===''?null:number(e.offered_requests,'Offered requests',{integer:true}),unresolved_or_censored:e.unresolved_or_censored===''?null:number(e.unresolved_or_censored,'Unresolved/censored work',{integer:true})};}catch(err){return {...out,status:'INVALID',message:err.message};}
}
function aggregateGroups(groups){if(!Array.isArray(groups))throw Error('Groups must be an array');let total=0,completed=0;for(const g of groups){keysExact(g,['reference_work','overhead','completed'],'Group');total+=number(g.reference_work,'Group reference work')+number(g.overhead,'Group overhead');completed+=number(g.completed,'Completed comparisons',{integer:true});}return {total_reference_control_work:total,completed_comparisons:completed,cost_per_completion:completed?total/completed:null,status:completed?'CALCULATED':'UNDEFINED_ZERO_COMPLETIONS'};}
function composeQuantities(a,b){for(const q of [a,b]){keysExact(q,['value','unit','scope','environment','timing_boundary','status'],'Quantity');if(!QUANTITY_STATUS.includes(q.status)||!text(q.unit,100)||!q.unit.trim()||!text(q.scope,300)||!q.scope.trim()||!text(q.environment,300)||!q.environment.trim()||!text(q.timing_boundary,100)||!q.timing_boundary.trim())throw Error('Invalid scoped quantity');}if(a.unit!==b.unit)throw Error('Cannot compose different units');if(a.scope!==b.scope)throw Error('Cannot compose different scopes');if(a.environment!==b.environment)throw Error('Cannot compose cross-environment observations without an explicit model');if(a.timing_boundary!==b.timing_boundary)throw Error('Cannot compose wall latency with active resource occupancy');return {value:number(a.value,'First quantity')+number(b.value,'Second quantity'),unit:a.unit,scope:a.scope,environment:a.environment,timing_boundary:a.timing_boundary,status:a.status===b.status?a.status:'user_assumed'};}
function legacyBaselineA(d){const l=d.legacy_sharing_scenario;if(!l)return null;try{return {variant:'A',reference_work_per_admitted_job:[number(l.ref_lo,'Legacy R low'),number(l.ref_hi,'Legacy R high')],provenance:'legacy user-entered v0.1 assumption',note:'One full reference pack is charged for each separately admitted job. This is not a measured cost or qualified exam.'};}catch(_){return {variant:'A',reference_work_per_admitted_job:null,provenance:'legacy v0.1 input incomplete or invalid',note:'No numeric baseline derived.'};}}
function selectedDynamic(d,study){const rows=study.dynamic.rows.filter(r=>r.scenario===d.dynamic_scenario.scenario&&String(r.assumed_group_overhead)===String(d.dynamic_scenario.overhead));return {scenario:d.dynamic_scenario.scenario,overhead:d.dynamic_scenario.overhead,units:study.dynamic.units,rows:rows.map(r=>({variant:r.variant,total_recurring_work:r.total_recurring_work,complete_comparisons:r.complete_comparisons,unfinished_or_nonpositive:r.unfinished_or_nonpositive,mean_feedback_delay:r.mean_feedback_delay,p95_feedback_delay:r.p95_feedback_delay,groups:r.groups.map(g=>g.members),group_timing:r.groups.map(g=>({members:g.members,dispatch_at:g.dispatch_at,closed_at:g.closed_at,fill_wait:g.fill_wait})),jobs:Object.entries(r.jobs).map(([job_id,j])=>({job_id,ordinary_queue_delay:j.ordinary_queue_delay,intentional_fill_delay:j.intentional_fill_delay,waiting_for_other_members:j.waiting_for_other_members,submission_to_summary:j.submission_to_summary,outcome:j.outcome})),reference_readiness:'NOT_SEPARATELY_RECORDED_IN_THIS_REPLAY',work:r.work})),warning:d.dynamic_scenario.scenario==='slow_or_unresolved_member'?'Lower total work accompanies fewer completed summaries; it is not equivalent productive throughput.':'Counterfactual research simulation; not a service recommendation.'};}
function nextAction(d,study){for(const meta of study.entry_conditions){const v=d.next_evidence[meta.id],missing=GAP_FIELDS.filter(k=>!v[k].trim());if(missing.length)return {condition:meta.id,question:meta.question,missing_input:missing.join(', '),source_owner:v.source_owner||meta.default_owner,smallest_observation:v.smallest_observation||'Record the smallest scoped observation or owner decision for this condition.',why_it_could_change_the_decision:v.why_decision_changes||'It may determine whether Variant B deserves a separately authorized experiment.',status:'MISSING'};}return {condition:'all',question:'Should Carbon commission a separately authorized Variant B experiment?',missing_input:'Domain review and retained protection blockers',source_owner:'Named domain owners',smallest_observation:'Review the assembled six-condition packet against the five unresolved protected-use claims.',why_it_could_change_the_decision:'A bounded experiment may be justified, but runtime implementation and activation remain unapproved.',status:'PACKET_ASSEMBLED'};}
function analysisRecord(d,study){const protection=protectionReview(d),economics=fixedGroupEconomics(d.reference_economics),dynamic=selectedDynamic(d,study),next=nextAction(d,study);return {schema_version:'carbon.workbench.challenge-analysis.v1',opportunity_id:d.opportunity_id,source_sha256:d.source_sha256,current_baseline:study.current_baseline,research_recommendation:study.recommendation,protection,economics,legacy_variant_a:legacyBaselineA(d),dynamic_research_view:dynamic,next_review_action:next,study:{study_id:study.study_id,evidence_version:study.evidence_version,delivery:study.provenance.delivery,evidence_index_sha256:study.provenance.evidence_index_sha256,qualified_carbon_evidence:null},authority:study.authority_disclaimer};}
function clientProjection(d,study,title){const a=analysisRecord(d,study),brief={...d.brief};delete brief.contact;return {schema_version:'carbon.workbench.client-summary.v1',title:title||d.opportunity_id,opportunity_id:d.opportunity_id,current_recommendation:'Retain Variant A in DEVELOPMENT. Variant B is a conditional research-review option only.',protection_state:a.protection.state,unresolved_protection:a.protection.unresolved_blockers,conditional_economics:a.economics,feedback_effect:a.dynamic_research_view.warning,next_discussion:a.next_review_action,client_context:brief,study_reference:a.study,authority:'Plain-language planning summary only. It is not a qualification, binding quote, submission, permission, or runtime command. Local exports are unencrypted; keep them non-sensitive.'};}
function engineeringProjection(d,study,title){const a=analysisRecord(d,study);return {schema_version:'carbon.workbench.engineering-review-packet.v1',title:title||d.opportunity_id,analysis:a,compatibility_and_evidence_conditions:study.entry_conditions.map(m=>({id:m.id,question:m.question,default_owner:m.default_owner,...d.next_evidence[m.id]})),controls:study.controls.map(c=>({...c,...d.protection.controls[c.id]})),study_blockers:study.attacks.filter(x=>BLOCKER_IDS.includes(x.attack_id)),all_attack_refs:study.attacks.map(x=>({attack_id:x.attack_id,control:x.control,current_disposition:x.current_disposition,implementation_layer:x.implementation_layer,counterexample_trace:x.counterexample_trace,limitation:x.limitation})),publication_review:d.protection.publication_review,authority:'Requests human review only. It cannot implement or activate runtime sharing, publish answers, qualify an exam, grant rights, change rewards, or create an official profile.'};}
function markdownProjection(v){const lines=['# '+v.title,'',v.authority,''];if(v.current_recommendation){lines.push('## Current recommendation','',v.current_recommendation,'','## Protection review','',`State: ${v.protection_state}. Unresolved study claims: ${v.unresolved_protection.join(', ')||'none recorded'}.`,'','## Conditional economics','',v.conditional_economics.message||'Unknown.','',`Scenario basis: ${JSON.stringify(v.conditional_economics)}`,'','## Next discussion','',`${v.next_discussion.question} Missing: ${v.next_discussion.missing_input}. Owner: ${v.next_discussion.source_owner}. Smallest observation: ${v.next_discussion.smallest_observation}`);}else{lines.push('## Current baseline','',`${v.analysis.current_baseline.variant} — ${v.analysis.current_baseline.environment}. ${v.analysis.current_baseline.description}`,'','## Protection and economics','',`Protection: ${v.analysis.protection.state}. Economics: ${v.analysis.economics.message}`,'','## Next review action','',JSON.stringify(v.analysis.next_review_action,null,2),'','## Exact planning record','','```json',JSON.stringify(v,null,2),'```');}return lines.join('\n')+'\n';}

const api={VERSION,WORKSPACE_VERSION,APP_VERSION,LEGACY_DRAFT_VERSION,LEGACY_WORKSPACE_VERSION,CHECKS,STATES,PLANNING,INPUTS,BRIEF,ROLES,CONTROL_IDS,CONTROL_STATES,BLOCKER_IDS,APPLICABILITY,QUANTITY_STATUS,ECON_UNITS,ECON_FIELDS,GAP_IDS,GAP_FIELDS,AUTHORITY,number,interval,maxCompleted,profile,margin,newDraft,validateDraft,strictJsonParse,readWorkspace,triage,protectionReview,fixedGroupEconomics,aggregateGroups,composeQuantities,legacyBaselineA,selectedDynamic,nextAction,analysisRecord,clientProjection,engineeringProjection,markdownProjection,validateEvidenceClaim};
if(typeof module!=='undefined'&&module.exports)module.exports=api;root.CarbonFit=api;
})(typeof globalThis!=='undefined'?globalThis:this);
