// Commercial research proposals, not registered Challenge IDs or reward policy.
export const evidenceRevision = "59d0fd589895557db607d228689010e65b6a33b5";
export const reviewedDate = "3 October 2026";
const repo = (path) => `https://github.com/carbonphysicsai/Carbon/blob/${evidenceRevision}/${path}`;
export const sources = {
  roadmap: { label: "26-family research roadmap", url: repo("Design_Specs/Challenge_Roadmap.md") },
  pipeline: { label: "Challenge pipeline and sequencing", url: repo("docs/development/CHALLENGE_PIPELINE.md") },
  canon: { label: "Business and network principles", url: repo("Business/Business_Canon.md") },
  budgets: { label: "Training-budget study requirement", url: repo("docs/development/CHALLENGE_TRAINING_BUDGET_STUDY.md") },
  cooling: { label: "Cold-plate development examination", url: repo(".agent/tickets/CHALLENGE-COLD-PLATE-01_development_exam.md") },
  optics: { label: "Existing photonic reference and its limits", url: repo(".agent/tickets/CHALLENGE-PHOTONIC-01_repair_and_reference.md") },
  battery: { label: "Battery reference contract", url: repo("carbon/battery/domain.py") },
  batteryCost: { label: "Historical battery reference cost", url: repo("docs/development/EXAM_DESIGN_CAMPAIGN_RESULT.md") },
  batteryValue: { label: "Battery decision-value study", url: repo("docs/development/BATTERY_ENGINEERING_VALUE_EV4.md") },
  motor: { label: "Full motor development examination", url: repo(".agent/tickets/CHALLENGE-MOTOR-01_development_exam.md") },
  science: { label: "Scientific evidence and claim boundaries", url: repo("docs/context/SCIENTIFIC_REFERENCE_CANON_V4_MASTER.md") },
};

export const programs = [
  {
    id: "cooling", number: "01", group: "compute", groupLabel: "AI hardware", role: "Commercial flagship", title: "AI accelerator cooling", short: "More cooling. Less pumping.",
    decision: "Choose cold-plate channels and coolant flow that meet a hotspot-temperature requirement with lower hydraulic power.",
    driver: "Repeated geometry changes make a reusable design model more valuable than a one-off fast prediction.",
    buyer: "Cold-plate manufacturers, server OEMs and accelerator thermal teams. Thermal engineering is the technical entry point; an R&D or product owner must establish a real budget.",
    paidEntry: "A finite Evidence Audit or feasibility study of a channel-design workflow, followed by sponsored model development if the current method has a costly, measurable gap.",
    economics: "The addressable job is screening and refining a family of designs, not replacing every CFD calculation. Potential value comes from less engineering wait time, more verified design iterations and, only if a design is tested, lower pumping burden. Better component predictions alone do not establish data-center energy savings.",
    repeat: "New heat maps, package layouts, coolant conditions and product variants could reuse an adapter and trigger model updates or re-evaluation. That is the recurring-work hypothesis; it is not contracted demand.",
    baseline: "Physics-aware channel correlations, thermal-resistance networks, cached calculations and an optimized conjugate heat-transfer design workflow.",
    contest: "Select a manufacturable geometry and flow setting under the same pumping, temperature and geometry constraints. Independently check the chosen design for feasibility and hydraulic objective; count the full search and checking costs.",
    scope: "Begin with bounded single-phase laminar flow and solid conduction. The existing straight periodic microchannel model excludes headers and manifolds. Coupled manifold design needs a new, verified reference contract before it can enforce temperature constraints.",
    reference: "OpenFOAM. Reuse the existing channel work, then qualify any new geometry, flow distribution and thermal coupling. Generic flow-only predictions cannot certify a hotspot temperature.",
    status: "Existing bounded reference work", evidence: "The current cold-plate development study supports a channel examination, not a commercial manifold model. Its learned baseline showed only a small aggregate advantage over a closed form and a worse temperature-profile prediction. No decisive design-workflow win is established.",
    next: "Measure complete channel-design economics against the strong closed form; verify the coupled reference before widening geometry.",
    pause: "Pause acceleration investment if the inexpensive baseline already reaches the same verified design at lower total cost, or if realistic coupling and manufacturability remove the advantage.",
    experiment: "Calibrated inlet temperature, heat input, pressure, flow and temperature measurements on an instrumented plate; predict new operating conditions before observing them.",
    expansions: ["Headers and manifold distribution", "Tolerance-aware coolant routing", "Customer-specific plate families", "System integration with new evidence"],
    sources: ["cooling", "pipeline"],
  },
  {
    id: "thermal", number: "02", group: "compute", groupLabel: "AI hardware", role: "First reality-learning pilot", title: "Burst-power thermal envelopes", short: "Know the thermal room to move.",
    decision: "Choose a burst-power schedule that delivers useful work while respecting a declared temperature envelope and recovery requirement.",
    driver: "Operational decisions repeat frequently; measurement can reveal contact and boundary effects an idealized solver misses.",
    buyer: "Accelerator, server and power-management engineering teams. This shares a customer conversation with cooling, but is a separate dynamic physical task.",
    paidEntry: "A scoped thermal-model audit or an instrumented heater/plate feasibility program, followed by device-specific model development where measurements support it.",
    economics: "The value hypothesis is less conservative operation within an evidenced thermal envelope and faster evaluation of power schedules. We must compare the complete decision workflow, not claim throughput gains from a temperature model alone. Cheap calibrated dynamics may already solve the problem.",
    repeat: "Power histories, package/contact changes, cooling boundaries and runtime revisions could create recurring calibration and lifecycle work. Expansion into scheduling or control needs additional system evidence.",
    baseline: "Calibrated thermal RC networks, analytical conduction models and reduced-order dynamics. These can be extremely fast and are mandatory competitors.",
    contest: "Select a complete power schedule on an unseen waveform family. Verify its temperature trajectory, time to limit and recovery independently; measure useful work at the same registered constraints and resource budget.",
    scope: "Layered-solid transient conduction with specified contact and boundary conditions. No boiling, thermal runaway or whole-data-center scheduler claim. All causal inputs and the initial state must be available.",
    reference: "Proposed Elmer transient thermal reference, with an appropriate independent analytical or numerical witness on selected cases. Solver availability is not reference qualification.",
    status: "New task proposed", evidence: "This is a proposed extension, not an implemented or experimentally validated Carbon challenge. It is the preferred first owned experiment because the input power and measured temperature can be controlled and recorded directly.",
    next: "Define and verify a layered-plate task, benchmark calibrated RC models, then price and approve a prospective instrumented pilot.",
    pause: "Do not fund a larger learned model if calibrated RC dynamics meet the decision requirement more cheaply. Do not infer identifiable material or contact parameters from an ambiguous sensor fit.",
    experiment: "An owned heater/plate rig. Commit forecasts before a held-out power schedule runs; separate frozen-model forecasting from any explicitly versioned online adaptation.",
    expansions: ["Device-specific thermal dynamics", "Contact and boundary calibration", "Power-envelope lifecycle updates", "Control support after separate qualification"],
    sources: ["roadmap", "science"],
  },
  {
    id: "photonics", number: "03", group: "compute", groupLabel: "AI hardware", role: "Frontier technology bet", title: "Manufacturing-tolerant optical coupling", short: "Design for variation, not one perfect device.",
    decision: "Choose a bounded 3D fiber-to-chip grating coupler with low loss and useful bandwidth across declared fabrication and alignment variations.",
    driver: "Robust design searches repeat full-wave calculations across geometry, wavelength and tolerances; one nominal optimum is not the engineering job.",
    buyer: "Silicon-photonics, optical-packaging and interconnect engineering teams. A component design program is the entry, not a claim to model an entire co-packaged optics system.",
    paidEntry: "A reference/feasibility study for one material stack and port definition, then sponsored robust-design research and a rights-cleared fabrication/measurement program.",
    economics: "The prospective advantage is more verified tolerance-aware design options per research budget. Full-wave cost can make repeated search attractive, but adjoint optimization may drastically reduce the solver burden. Fabrication, metrology and process-distribution acquisition can dominate the real economics.",
    repeat: "New stacks, alignment envelopes, bands and packaging variants may reuse methods and evidence workflows. Commercial re-use depends on stack access, rights and actual process measurements.",
    baseline: "Adjoint optimization, lower-dimensional screening, interpolation and optimized full-wave verification. Do not compare only with brute-force parameter sweeps.",
    contest: "Select a grating geometry for a declared tolerance distribution and wavelength band. Verify selected devices with converged 3D calculations. Synthetic robustness becomes a manufacturing claim only after actual process and optical evidence.",
    scope: "Fixed material stack, polarization, band and port conventions; bounded manufacturable geometry. Numerical loss and coupling require qualified normalization, phase, boundaries and convergence.",
    reference: "Proposed Meep full-wave FDTD; an existing fdtdx GPU path is a feasibility candidate, not automatic truth. Pin CPU/GPU profiles separately and qualify any primary/witness role.",
    status: "New full-wave task proposed", evidence: "Carbon's existing symmetric coupler is a cheap, lower-dimensional internal test. It does not substantiate the commercial 3D grating task. Retain it as a regression asset; replace it as the headline use case.",
    next: "Demonstrate converged full-wave outputs and realistic fabrication bounds, then measure a robust-design workflow against an adjoint baseline.",
    pause: "Pause if an optimized adjoint workflow wins on verified design quality and cost, or if fabrication access and rights prevent a credible experimental path.",
    experiment: "Measured geometry and optical transmission on fabricated devices, with held-out devices and declared alignment conditions. Do not label a synthetic tolerance score as manufacturing yield.",
    expansions: ["Packaging alignment robustness", "New registered material stacks", "Other grating and coupling families", "Optical-I/O component workflows"],
    sources: ["optics", "roadmap"],
  },
  {
    id: "battery", number: "04", group: "energy", groupLabel: "Battery engineering", role: "Retained development asset", title: "Cell-specific fast charging", short: "Charge time is only half the decision.",
    decision: "Choose a charging protocol that reduces charge time within declared voltage, temperature and degradation constraints for one cell envelope.",
    driver: "Useful protocols trade speed against degradation; repeated cell and schedule studies can amortize a reusable model.",
    buyer: "Cell manufacturers, battery R&D teams and OEM battery/BMS engineers. The hypothesis is a bounded cell-development program, not universal charging software.",
    paidEntry: "Audit a charging/ageing decision workflow or integrate an available cell reference, then sponsor cell-specific model and experiment development.",
    economics: "Model-guided protocol selection could reduce simulation and experimental search effort. That is valuable only when selected schedules survive independent feasibility checks. Real-cell cycling, replication and diagnostic costs must be included; an optimistic boundary prediction can erase a nominal compute saving.",
    repeat: "Chemistry, batch, temperature, geometry and protocol changes could create recurring calibration and re-evaluation. Full lifetime and pack operation require new contracts and evidence.",
    baseline: "CCCV rules, calibrated reduced battery models, interpolation, direct schedule optimization and established experimental-design methods.",
    contest: "Commit a charging protocol before fresh independent assessment. Compare verified charge time at the same constraints, including false-feasible selections, capacity outcomes and complete search/verification costs.",
    scope: "Retain the existing PyBaMM charging-plus-ageing scope: 30 simulated cycles, voltage/temperature trajectories, plating margin and specified capacity checkpoints. It is not full lifetime, real-cell safety or measured plating truth.",
    reference: "Existing PyBaMM DFN with the pinned ageing and thermal formulation. A future experimental contract must define cell identity, diagnostics, replication and its assessment horizon.",
    status: "Existing development contract", evidence: "Battery is the protocol-development lead. The decision-value studies retain feasibility-boundary and localized prediction concerns; no commercial or experimentally grounded charging superiority is established.",
    next: "Complete the battery-led challenge protocol and resolve decision-value findings before admitting broader tasks or expanding the charging claim.",
    pause: "Do not promote a faster protocol when independent checks find constraint violations. Voltage and temperature alone cannot establish absence of lithium plating.",
    experiment: "Supervised, replicated cell tests with held-out protocols and batches, rights-cleared diagnostics and predictions committed before outcomes. This page authorizes no charging or hardware control.",
    expansions: ["Measured cell-specific calibration", "Batch and temperature variation", "Richer thermal geometry", "Lifetime or pack tasks only with new evidence"],
    sources: ["battery", "batteryValue", "pipeline"],
  },
  {
    id: "motors", number: "05", group: "motion", groupLabel: "Precision motion", role: "Retained development asset", title: "Low-ripple precision motors", short: "Optimize the entire torque curve.",
    decision: "Choose bounded motor geometry and current for low torque variation while retaining the required mean torque.",
    driver: "The job is a multi-angle design search, not one cheap magnetic snapshot; geometry changes create repeated analysis.",
    buyer: "Precision actuator, robotics and motor-design teams. Electromagnetic design is the initial scope; full robot motion quality requires system evidence.",
    paidEntry: "A torque-prediction or design-workflow audit, followed by sponsored bounded motor optimization and measured validation of shortlisted designs.",
    economics: "The opportunity is faster exploration of acceptable geometry/current combinations and fewer poor designs sent to prototype. A torque-ripple improvement must survive independent analysis and tolerances; it cannot be priced as an efficiency, acoustic or robot-throughput improvement without those measurements.",
    repeat: "New geometric families, current conditions and measured material curves could support repeat development and lifecycle work. Reusable meshing/evaluation reduces delivery effort only if demonstrated across actual programs.",
    baseline: "Analytical harmonic models, interpolation, reduced magnetic models and optimized multi-angle electromagnetic analysis.",
    contest: "Select a geometry/current combination from the same bounds. Independently verify the full torque-angle curve, mean torque and ripple objective, accounting for saturation and critical mesh regions.",
    scope: "Existing bounded 2D 8-pole/24-slot motor with a 60-angle torque curve and declared iron law. No automatic 3D end-effect, thermal, efficiency-map or assembly-level precision claim.",
    reference: "Existing pinned GetDP and Gmsh path with refinement checks. Measured material laws and any new 3D or loss model require separate reference adequacy.",
    status: "Existing bounded reference work", evidence: "The full-curve development study showed a learned baseline improving aggregate error against its analytical comparator, but retained substantial ripple error and a reference-invalid case. This is not commercial precision qualification.",
    next: "Measure complete design-search value, close ripple/tail concerns and test independently checked selected designs.",
    pause: "Pause if curve-level improvements fail to select better feasible motors, or if a cheap reduced model provides the same decision at lower cost.",
    experiment: "Measured steel response and calibrated current/torque-angle tests, with unseen geometries or devices and explicit fixture uncertainty.",
    expansions: ["Measured material curves", "Tolerance-aware torque design", "3D end effects as a new task", "Loss and thermal coupling with new qualification"],
    sources: ["motor", "roadmap"],
  },
  {
    id: "vibration", number: "06", group: "motion", groupLabel: "Precision motion", role: "Shared customer expansion", title: "Resonance-resistant structures", short: "Put stiffness where the motion needs it.",
    decision: "Choose a precision-stage support or robot-link geometry with low dynamic response in the excitation band, subject to mass and stiffness constraints.",
    driver: "Geometry variation and uncertain damping create a richer job than a fast frequency sweep on one fixed mesh.",
    buyer: "Precision-automation, motion-stage and robotics engineering teams. This can expand the motor conversation without treating motor and structural evidence as interchangeable.",
    paidEntry: "A dynamic-response model audit or bounded variable-geometry feasibility study, then a design program tied to a customer's measured excitation and supports.",
    economics: "Potential value is less redesign and faster selection of structures that avoid critical resonances. A fixed-geometry modal sweep is often inexpensive: the investment case depends on variable geometry, reusable evidence or a demonstrated improvement against measured behavior, not deliberately slow solver settings.",
    repeat: "Payload, support, damping and assembly changes can create new evidence work. Repeated product-family studies could justify lifecycle tools after delivery effort and demand are measured.",
    baseline: "Modal superposition, efficient factorization reuse, analytical beams and reduced-order models across geometry changes.",
    contest: "Select a geometry under common mass, stiffness and excitation constraints. Independently verify peak complex response and near-resonance behavior; compare against a tuned modal workflow.",
    scope: "Linear elasticity with explicitly defined excitation, support and damping. No nonlinear impact, fatigue, full-machine settling-time or throughput claim.",
    reference: "Proposed CalculiX modal/harmonic analysis with mesh and frequency refinement, supported by analytical controls. Static stress and modal families are foundations, not additional headline slots.",
    status: "New task proposed", evidence: "A roadmap family and an available solver do not constitute an implemented Carbon challenge. The variable-geometry decision and reference adequacy still need to be defined and tested.",
    next: "Demonstrate a meaningful variable-geometry job and benchmark a strong modal baseline before building a large learned-model study.",
    pause: "Pause if fast modal methods already answer the job, or if unobserved damping/support behavior makes the proposed model underdetermined.",
    experiment: "Calibrated force and accelerometer measurements on a structure, held out by geometry or assembly. Fit and forecast data must remain separate.",
    expansions: ["Measured joints and damping", "Payload and support variants", "Precision-machine assemblies", "Broader dynamics with new reference scope"],
    sources: ["roadmap", "science"],
  },
  {
    id: "acoustics", number: "07", group: "industry", groupLabel: "Industrial equipment", role: "Bounded industry wedge", title: "Compact compressor silencers", short: "Attenuation within a real package.",
    decision: "Choose a passive multichamber duct geometry for attenuation across a declared source band within packaging limits.",
    driver: "Geometry, termination and source-band changes recur, but a transfer-matrix model may already be the best investment.",
    buyer: "Industrial compressor and equipment acoustic-design teams. A component silencer study is the entry; the model does not generate the compressor's noise source.",
    paidEntry: "A linear-acoustic feasibility or model-evidence study, followed by component design and a measured duct-rig program if the baseline leaves a valuable gap.",
    economics: "A reusable design workflow could shorten acoustic iteration and reduce failed prototypes. The first cost test is against transfer matrices and modal methods. Backpressure and operating energy are separate checks; a linear acoustic score cannot establish those savings.",
    repeat: "Source spectra, packaging, termination and product variants may yield repeat programs. Operating-flow acoustics is a later scope, not an included feature.",
    baseline: "Transfer-matrix methods, modal acoustics and optimized 3D acoustic verification on designs where the simpler representation is inadequate.",
    contest: "Select a chamber/duct geometry within the same package constraints. Independently verify band attenuation and complex response, with pinned source and termination assumptions.",
    scope: "Linear passive acoustics under declared boundary impedances. No turbulent noise generation, flow-induced effects or pressure-loss prediction.",
    reference: "Proposed Elmer Helmholtz reference, with qualified analytical controls and a possible independent GetDP witness on difficult cases.",
    status: "New task proposed", evidence: "The challenge remains a proposal. No Carbon silencer reference examination, experimentally verified design or customer ROI is claimed.",
    next: "Show that a realistic compact geometry creates a valuable decision beyond the transfer-matrix baseline, then verify the acoustic reference.",
    pause: "Use the cheap method if it already solves the job. Do not sell an acoustic-only optimum as a viable compressor component without separate flow and integration checks.",
    experiment: "A calibrated duct rig measuring transfer response with declared source and termination conditions, with unseen geometries and repeat measurements.",
    expansions: ["Source and termination variants", "Customer packaging families", "Operating-flow acoustics as a new task", "Coupled pressure-loss/integration checks"],
    sources: ["roadmap", "science"],
  },
  {
    id: "mixing", number: "08", group: "lab", groupLabel: "Lab and process automation", role: "Measured-transport expansion", title: "Passive micromixer cartridges", short: "Mix uniformly before the outlet.",
    decision: "Choose passive groove/channel geometry and flow for uniform outlet concentration within a length or residence-time requirement.",
    driver: "A measured transport task can link device design to observable outcomes while reusing qualified flow and diffusion foundations.",
    buyer: "Microfluidic cartridge, lab-automation and process-equipment developers. This is a component-design opportunity, not a clinical or drug-development claim.",
    paidEntry: "A passive-mixing reference or model audit, followed by a bounded cartridge-design program and tracer measurements where the economics justify it.",
    economics: "Potential value is quicker cartridge iteration and fewer physical design trials. The full cost includes the velocity-field solve and transport accuracy; artificial numerical diffusion cannot count as better mixing. Simple channels may favor analytical or reduced models.",
    repeat: "Flow rates, diffusivities and cartridge families may create repeat evaluation and adaptation. Reuse across customers depends on geometry rights and experimental comparability.",
    baseline: "Analytical diffusion/channel estimates, network transport models, reduced-order models and optimized flow-plus-transport simulation.",
    contest: "Select a manufacturable cartridge and flow setting. Independently check outlet concentration uniformity at the same residence/length constraints, including the cost and uncertainty of the velocity solution.",
    scope: "Laminar incompressible flow with passive scalar transport and declared diffusivity. No reaction yield, cell viability, clinical performance or chemical kinetics claim.",
    reference: "Proposed OpenFOAM flow and scalar-transport path. Qualify Peclet behavior, conservation, positivity and numerical diffusion; count flow solving rather than hiding it as free input.",
    status: "New task proposed", evidence: "This is a design proposal, not a verified Carbon micromixer model. The flow, transport and measurement contracts require their own feasibility and reference work.",
    next: "Verify flow-plus-transport controls, compare an inexpensive mixing baseline and define an observable cartridge task before scaling research.",
    pause: "Pause if low-cost transport estimates solve the decision or if measurement/solver diffusion obscures the actual physical mixing advantage.",
    experiment: "Calibrated fluorescence or tracer observations, with an explicit sensor/observation model and whole cartridges or experiments held out.",
    expansions: ["New passive cartridge families", "Measured transport calibration", "Lab automation integration", "Reaction tasks only under new contracts"],
    sources: ["roadmap", "science"],
  },
];
