// Explicit operating scenarios, not measured model results or total ROI.
export const screeningScenario = Object.freeze({ designs: 1000, solverChecks: 20, predictionSeconds: 0.1, dollarsPerRunHour: 5 });
export const highlights = [
  { id: "cooling", title: "AI accelerator cooling", highlight: "More compute. Less pumping.", industry: "Screen cold-plate channel designs for AI servers with hotspot-temperature and pumping constraints.", customers: "Cold-plate manufacturers · Server OEMs", solverSeconds: 1200, baseline: "20 min / design", basis: "Illustrative manifold-flow estimate from roadmap f04; not current cold-plate timing.", source: "roadmap", state: "Foundation + proposed expansion" },
  { id: "thermal", title: "Burst-power thermal envelopes", highlight: "Find the thermal room to move.", industry: "Compare chip power schedules to predict temperature limits, burst duration and recovery.", customers: "Accelerator teams · Power-management engineers", solverSeconds: 120, baseline: "2 min / schedule", basis: "Illustrative transient-thermal estimate from roadmap f02; RC models may be much faster.", source: "roadmap", state: "Proposed research" },
  { id: "photonics", title: "Manufacturing-tolerant optical coupling", highlight: "Design for variation, not perfection.", industry: "Screen 3D fiber-to-chip grating designs across wavelength, alignment and fabrication variation.", customers: "Silicon-photonics teams · Optical-packaging firms", solverSeconds: 480, baseline: "8 min / device case", basis: "Illustrative 3D FDTD estimate from roadmap f06; not the existing symmetric coupler or an adjoint workflow benchmark.", source: "roadmap", state: "Proposed full-wave expansion" },
  { id: "battery", title: "Cell-specific fast charging", highlight: "Faster charging. Degradation in view.", industry: "Search charging protocols that trade charge time against voltage, temperature and ageing constraints.", customers: "Cell manufacturers · OEM battery teams", solverSeconds: 71, baseline: "71 sec / 30-cycle case", basis: "Historical 30-cycle battery study median; not a current standardized timing or real-cell safety result.", source: "batteryCost", state: "Protocol development" },
  { id: "motors", title: "Low-ripple precision motors", highlight: "Optimize the whole torque curve.", industry: "Screen motor geometry and current for smooth torque while retaining required mean torque.", customers: "Actuator manufacturers · Robotics motor teams", solverSeconds: 480, baseline: "8 min / torque curve", basis: "Illustrative 60 angles × roadmap f09's estimate of 8 seconds per angle; not a measured full-case benchmark.", source: "roadmap", state: "Bounded reference work" },
  { id: "vibration", title: "Resonance-resistant structures", highlight: "Put stiffness where motion needs it.", industry: "Compare robot-link and precision-stage geometries under mass, stiffness and vibration constraints.", customers: "Precision-automation firms · Motion-stage OEMs", solverSeconds: 300, baseline: "5 min / sweep", basis: "Illustrative direct-solve frequency-sweep estimate from roadmap f08; efficient modal reduction may erase the advantage.", source: "roadmap", state: "Proposed research" },
  { id: "acoustics", title: "Compact compressor silencers", highlight: "Less noise. Within the package.", industry: "Screen passive chamber and duct layouts for attenuation across a declared acoustic source band.", customers: "Compressor manufacturers · Industrial OEMs", solverSeconds: 90, baseline: "90 sec / acoustic case", basis: "Illustrative Helmholtz estimate from roadmap f13; not pressure-loss prediction or a transfer-matrix benchmark.", source: "roadmap", state: "Proposed research" },
  { id: "mixing", title: "Passive micromixer cartridges", highlight: "Uniform mixing before the outlet.", industry: "Compare channel grooves and flow settings for outlet uniformity within residence-time constraints.", customers: "Microfluidic developers · Lab-automation firms", solverSeconds: 120, baseline: "2 min / transport case", basis: "Illustrative transport estimate from roadmap f17; any separately required flow solve must also be counted.", source: "roadmap", state: "Proposed research" },
];

export function screeningImpact(solverSeconds, scenario = screeningScenario) {
  if (!Number.isFinite(solverSeconds) || solverSeconds <= 0) throw new RangeError("Solver time must be positive.");
  const { designs, solverChecks, predictionSeconds, dollarsPerRunHour } = scenario;
  if (!Number.isInteger(designs) || !Number.isInteger(solverChecks) || designs < 1 || solverChecks < 0 || solverChecks > designs || !Number.isFinite(predictionSeconds) || predictionSeconds < 0 || !Number.isFinite(dollarsPerRunHour) || dollarsPerRunHour < 0) throw new RangeError("Invalid screening scenario.");
  const baselineSeconds = designs * solverSeconds;
  const surrogateSeconds = designs * predictionSeconds + solverChecks * solverSeconds;
  const runHoursSaved = (baselineSeconds - surrogateSeconds) / 3600;
  return { baselineSeconds, surrogateSeconds, runHoursSaved, dollarsSaved: runHoursSaved * dollarsPerRunHour };
}
