import { programs, sources, evidenceRevision, reviewedDate } from "./content.mjs";

const escape = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const arrow = '<span aria-hidden="true">↗</span>';
const sourceLink = (key) => `<a href="${escape(sources[key].url)}" target="_blank" rel="noreferrer">${escape(sources[key].label)} ${arrow}</a>`;
const field = (heading, text, className = "") => `<div class="pf-field ${className}"><h4>${escape(heading)}</h4><p>${escape(text)}</p></div>`;

const card = (p) => `<article class="pf-card" data-group="${p.group}" aria-labelledby="${p.id}-title">
  <div class="pf-card-top"><span class="pf-index">${p.number}</span><span class="pf-category">${p.groupLabel}</span><span class="pf-role">${p.role}</span></div>
  <h3 id="${p.id}-title">${p.title}</h3><p class="pf-card-hook">${p.short}</p>
  <p class="pf-decision">${p.decision}</p><p class="pf-driver"><span>Economic thesis</span>${p.driver}</p>
  <div class="pf-card-status"><span class="pf-status-dot" aria-hidden="true"></span>${p.status}</div>
  <details class="pf-dossier" id="${p.id}"><summary>Explore the investment case <span class="pf-plus" aria-hidden="true">+</span></summary>
    <div class="pf-dossier-body">
      <p class="pf-dossier-kicker">${p.number} / Research investment case</p>
      <div class="pf-fields">${field("Who could buy", p.buyer)}${field("First commercial engagement", p.paidEntry)}${field("Where the economics could work", p.economics, "pf-field-wide")}${field("Why the work could recur", p.repeat)}${field("The strong alternative to beat", p.baseline)}${field("The fixed-resource design test", p.contest, "pf-field-wide")}${field("Physical scope and exclusions", p.scope)}${field("Open-source reference path", p.reference)}</div>
      <div class="pf-evidence"><h4>Evidence today</h4><p>${p.evidence}</p><h4>Next evidence milestone</h4><p>${p.next}</p></div>
      <div class="pf-fields">${field("Path to physical reality", p.experiment, "pf-field-wide")}${field("When we would pause", p.pause, "pf-field-wide pf-pause")}</div>
      <h4 class="pf-expansion-title">Potential expansions · not current capabilities</h4><ul class="pf-expansions">${p.expansions.map((x) => `<li>${escape(x)}</li>`).join("")}</ul>
      <div class="pf-card-sources"><span>Basis and scope</span>${p.sources.map(sourceLink).join("")}<a class="pf-permalink" href="#${p.id}">Link to this program ${arrow}</a></div>
    </div>
  </details>
</article>`;

export function renderPortfolio() {
  return `<!doctype html>
<html lang="en" data-page="portfolio">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Research Portfolio · Carbon</title>
  <meta name="description" content="Eight proposed research programs. The engineering decisions, economics, evidence milestones and industry expansion behind Carbon's Physics AI portfolio.">
  <link rel="canonical" href="https://carbonphysics.ai/portfolio/">
  <meta name="theme-color" content="#f5f5f0"><meta property="og:type" content="website"><meta property="og:site_name" content="Carbon">
  <meta property="og:title" content="Research Portfolio · Carbon"><meta property="og:description" content="Why these eight physics research bets. What could create value. What we still have to prove."><meta property="og:url" content="https://carbonphysics.ai/portfolio/">
  <meta property="og:image" content="https://carbonphysics.ai/assets/og-carbon.png"><meta name="twitter:card" content="summary_large_image">
  <link rel="icon" href="../favicon.svg" type="image/svg+xml">
  <link rel="preload" href="../assets/neue-0.otf" as="font" type="font/otf" crossorigin>
  <link rel="stylesheet" href="./portfolio.css"><script type="module" src="./portfolio.js"></script>
</head>
<body>
<a class="pf-skip" href="#main">Skip to content</a>
<header class="pf-header"><div class="pf-wrap pf-header-inner">
  <a class="pf-brand" href="https://carbonphysics.ai/" aria-label="Carbon home"><img src="../assets/brand-2.svg" alt="Carbon" width="172" height="40"></a>
  <nav class="pf-desktop-nav" aria-label="Main"><a href="https://carbonphysics.ai/investors/">Investors</a><a href="#portfolio" aria-current="page">Portfolio</a><a href="https://carbonphysics.ai/customers/">Customers</a><a href="https://carbonphysics.ai/miners/">Miners</a></nav>
  <a class="pf-header-contact" href="mailto:hello@carbonphysics.ai?subject=Carbon%20portfolio%20research">Discuss a program ${arrow}</a>
  <details class="pf-mobile-menu"><summary>Menu <span aria-hidden="true">+</span></summary><nav aria-label="Mobile"><a href="https://carbonphysics.ai/">Home</a><a href="https://carbonphysics.ai/investors/">Investors</a><a href="#portfolio">Portfolio</a><a href="https://carbonphysics.ai/customers/">Customers</a><a href="https://carbonphysics.ai/miners/">Miners</a><a href="mailto:hello@carbonphysics.ai">Discuss a program</a></nav></details>
</div></header>
<main id="main" tabindex="-1">
<section class="pf-hero" aria-labelledby="hero-title"><div class="pf-wrap">
  <div class="pf-eyebrow pf-hero-label"><span class="pf-live-dot" aria-hidden="true"></span>Carbon / Research portfolio</div>
  <div class="pf-hero-grid"><div><h1 id="hero-title">Physics worth<br>building<span class="pf-lime">.</span></h1><p class="pf-hero-lede">Eight research bets. One investment test: <strong>can we get to a better engineering decision, with evidence, at a lower total cost?</strong></p><div class="pf-hero-actions"><a class="pf-button pf-button-lime" href="#portfolio">Explore the eight <span aria-hidden="true">↓</span></a><a class="pf-hero-link" href="#economics">See the economics ${arrow}</a></div></div>
  <div class="pf-map" aria-label="Five customer clusters connect eight proposed research programs"><div class="pf-map-head"><span>Investment map</span><span>08 research programs</span></div>
    <a class="pf-map-row pf-map-compute" href="#cooling"><span>01—03</span><div><b>AI hardware</b><small>Cooling · burst power · optical I/O</small></div><span class="pf-map-arrow" aria-hidden="true">↗</span></a>
    <a class="pf-map-row" href="#battery"><span>04</span><div><b>Battery engineering</b><small>Charging decisions + degradation</small></div><span class="pf-map-arrow" aria-hidden="true">↗</span></a>
    <a class="pf-map-row" href="#motors"><span>05—06</span><div><b>Precision motion</b><small>Torque variation · structural resonance</small></div><span class="pf-map-arrow" aria-hidden="true">↗</span></a>
    <a class="pf-map-row" href="#acoustics"><span>07</span><div><b>Industrial equipment</b><small>Compact acoustic design</small></div><span class="pf-map-arrow" aria-hidden="true">↗</span></a>
    <a class="pf-map-row" href="#mixing"><span>08</span><div><b>Lab + process automation</b><small>Passive mixing cartridges</small></div><span class="pf-map-arrow" aria-hidden="true">↗</span></a>
    <div class="pf-map-foot"><span>One evidence standard.</span><span>No universal physics score.</span></div>
  </div></div>
  <div class="pf-hero-note"><span>Strategy snapshot / ${reviewedDate}</span><p>Proposed commercial research portfolio, not eight live products. Existing development evidence and new task proposals are labelled separately. No allocation, deployment, customer traction or solver superiority is claimed.</p></div>
</div></section>

<nav class="pf-section-nav" aria-label="On this page"><div class="pf-wrap"><a href="#thesis">Why these bets</a><a href="#portfolio">The portfolio</a><a href="#economics">Unit economics</a><a href="#comparison">Design competitions</a><a href="#network">Miner emissions</a><a href="#reality">Physical reality</a></div></nav>

<section class="pf-section pf-wrap" id="thesis" aria-labelledby="thesis-title"><div class="pf-section-heading"><p class="pf-eyebrow">01 / The selection thesis</p><h2 id="thesis-title">We invest in repeated decisions.<br>Not expensive simulations for their own sake.</h2><p class="pf-intro">A slow solver is not enough. A valuable industry is not enough. Each program needs a bounded physical job, a credible alternative, a path to measurements and a reason a customer would pay again.</p></div>
<div class="pf-thesis-grid"><div class="pf-thesis-card"><span>01</span><h3>Choose a real engineering job</h3><p>Geometry, schedules and operating conditions are decisions. Raw field prediction is a tool. We invest where a better model could change an actual design or operating choice.</p></div><div class="pf-thesis-card"><span>02</span><h3>Beat the cheapest competent route</h3><p>Compare against optimized solvers, reduced-order models, analytical methods and caching. Include data, training, calibration, verification and fallback—not just inference.</p></div><div class="pf-thesis-card"><span>03</span><h3>Build assets that can be reused</h3><p>A reference adapter, evidence workflow and rights-cleared method can support new variants. Reuse must reduce measured delivery effort; eight bespoke consulting projects are not the end state.</p></div></div>
<div class="pf-selection"><div><p class="pf-eyebrow">Portfolio planning lens</p><h3>Commercial merit first.<br>Network conviction matters.</h3><p>The selection gives Bittensor investor fit a <strong>25% planning weight</strong>: recognizable frontier problems, visible proof and a credible role for external research. The remaining 75% is commercial and technical judgment. These are qualitative planning weights, not a measured ranking or emissions formula.</p></div><div class="pf-weight"><div class="pf-weight-bar" role="img" aria-label="75 percent commercial and technical judgment; 25 percent Bittensor investor fit"><span></span><span></span></div><div class="pf-weight-label"><div><b>75%</b><span>Commercial + technical</span></div><div><b>25%</b><span>Bittensor investor fit</span></div></div><p>AI infrastructure is the lead narrative; battery and precision machines broaden the opportunity. Investor appeal never changes the scientific exam.</p></div></div>
<p class="pf-context-note">These eight customer-facing programs draw from the 26-family roadmap. Supporting stress, modal, magnetic and diffusion work is not counted as extra products. This proposal does not replace the repository's technical queue or Carbon's adopted sales strategy. ${sourceLink("roadmap")}</p>
</section>

<section class="pf-section pf-portfolio-section" id="portfolio" aria-labelledby="portfolio-title"><div class="pf-wrap"><div class="pf-section-heading pf-heading-row"><div><p class="pf-eyebrow">02 / Where the work could create value</p><h2 id="portfolio-title">The eight investment cases.</h2><p class="pf-intro">Open a program for the customer wedge, full economics, hard alternative, evidence gaps and expansion path. The two cooling tasks share a commercial story, not a scientific contract.</p></div><span class="pf-count-mark" aria-hidden="true">08</span></div>
<div class="pf-portfolio-toolbar" hidden><div class="pf-filters" role="group" aria-label="Filter programs by customer cluster"><button type="button" data-filter="all" aria-pressed="true">All eight</button><button type="button" data-filter="compute" aria-pressed="false">AI hardware</button><button type="button" data-filter="energy" aria-pressed="false">Battery</button><button type="button" data-filter="motion" aria-pressed="false">Precision motion</button><button type="button" data-filter="industry" aria-pressed="false">Industrial</button><button type="button" data-filter="lab" aria-pressed="false">Lab + process</button></div><button type="button" class="pf-expand-all" aria-pressed="false">Expand visible cases</button></div>
<p class="pf-results" role="status" aria-live="polite">8 research programs · no live result implied</p><div class="pf-card-grid">${programs.map(card).join("\n")}</div>
</div></section>

<section class="pf-section pf-wrap" id="economics" aria-labelledby="economics-title"><div class="pf-section-heading"><p class="pf-eyebrow">03 / The economic discipline</p><h2 id="economics-title">The win has to survive<br>the whole cost stack.</h2><p class="pf-intro">A model can predict in milliseconds and still be the more expensive choice. Research is justified by the total cost of reaching the same acceptable engineering decision, over a useful life.</p></div>
<div class="pf-cost-stack"><div><span>Build</span><p>Reference data · engineering · training · independent reconstruction · calibration</p></div><span class="pf-cost-plus" aria-hidden="true">+</span><div><span>Use</span><p>Search · inference · candidate verification · failed attempts · solver fallback</p></div><span class="pf-cost-plus" aria-hidden="true">+</span><div><span>Maintain</span><p>New data · rebuilds · re-evaluation · monitoring · rights-cleared integration</p></div></div>
<div class="pf-calculator"><div class="pf-calculator-copy"><p class="pf-eyebrow">Assumption explorer / not a forecast</p><h3>When could the model pay back?</h3><p>Change the inputs to see the break-even point. A “campaign” is one complete design or operating study—not one prediction. Costs must cover the same accepted job and include labor, compute, verification, failures and fallback.</p><div class="pf-calc-formula">Baseline = campaigns × baseline cost<br>Carbon route = build + upkeep + campaigns × model-route cost</div><p class="pf-calc-warning">All default numbers are illustrative USD assumptions, identical across programs. They are not Carbon measurements, prices, customer savings or an emission budget. Lower cost only matters if the decision meets the same independently checked requirements.</p></div>
<div class="pf-calculator-panel"><form id="pf-economic-form" novalidate><div class="pf-inputs">
  <label for="pf-build">Initial build + evidence cost <span>USD, one-time</span><input id="pf-build" name="build" type="number" inputmode="decimal" min="0" max="1000000000" step="0.01" value="50000" aria-describedby="pf-calc-error" disabled></label>
  <label for="pf-upkeep">Upkeep over the useful life <span>USD, total rebuilds + re-evaluation</span><input id="pf-upkeep" name="upkeep" type="number" inputmode="decimal" min="0" max="1000000000" step="0.01" value="10000" aria-describedby="pf-calc-error" disabled></label>
  <label for="pf-baseline">Best baseline per campaign <span>USD, complete accepted study</span><input id="pf-baseline" name="baseline" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="1200" aria-describedby="pf-calc-error" disabled></label>
  <label for="pf-model">Model route per campaign <span>USD, including checking + fallback</span><input id="pf-model" name="model" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="200" aria-describedby="pf-calc-error" disabled></label>
  <label class="pf-input-wide" for="pf-campaigns">Campaigns within the same valid envelope <span>Count over the model's useful life</span><input id="pf-campaigns" name="campaigns" type="number" inputmode="numeric" min="1" max="1000000" step="1" value="100" aria-describedby="pf-calc-error" disabled></label>
  </div><p id="pf-calc-error" role="alert" hidden></p></form>
  <div class="pf-calculator-results" aria-live="polite" aria-atomic="true"><div class="pf-break-even"><span>Illustrative break-even</span><strong id="pf-break-even">60 campaigns</strong><small id="pf-break-even-note">Cost parity; savings start above this count.</small></div><div class="pf-result-pair"><div><span>Baseline total</span><strong id="pf-baseline-total">$120,000</strong></div><div><span>Model-route total</span><strong id="pf-model-total">$80,000</strong></div></div><p id="pf-savings" class="pf-savings">$40,000 lower modeled cost across 100 campaigns.</p></div>
  <noscript><p class="pf-noscript">Enable JavaScript to change assumptions. The displayed example is static and illustrative: $60,000 fixed cost + 100 × $200 = $80,000 versus 100 × $1,200 = $120,000.</p></noscript>
</div></div>
<div class="pf-economics-foot"><p><strong>Don't count unearned savings.</strong> Energy, yield, faster charging, fewer prototypes or higher throughput require measured outcomes. This cost explorer excludes those speculative benefits.</p><p><strong>A fast solver is a legitimate winner.</strong> If a cheap reduced model solves the job, use it. Physical calibration may still justify research, but that is a separate thesis to test.</p></div>
</section>

<section class="pf-dark-section" id="comparison" aria-labelledby="comparison-title"><div class="pf-wrap"><div class="pf-section-heading"><p class="pf-eyebrow">04 / The proof investors should expect</p><h2 id="comparison-title">Not “AI vs. solver.”<br>A fair design competition.</h2><p class="pf-intro">Once the references and models are ready, we propose testing the engineering decisions they produce. No matched-resource portfolio competition results are published here yet.</p></div>
<div class="pf-comparison-grid"><div class="pf-comparison-main"><p class="pf-panel-label">Proposed comparison contract</p><ol class="pf-competition-steps"><li><span>01</span><div><h3>Freeze the job</h3><p>Same geometry or schedule bounds, constraints, allowed information and fresh held-out cases. Register the decision and failure rules before outcomes.</p></div></li><li><span>02</span><div><h3>Match the resources</h3><p>Declare hardware, elapsed-time and total-dollar budgets. For a model-only test, also match optimizer, initialization, query allowance and stopping rules. For a full-workflow test, allow each route its best method inside the same budget.</p></div></li><li><span>03</span><div><h3>Commit the selected design</h3><p>Each route submits its choice before independent reference checks. Include all data, training, search, retries, coordination, verification and fallback costs.</p></div></li><li><span>04</span><div><h3>Judge the actual decision</h3><p>Report verified feasible designs, objective quality, time/cost to a correct decision, false-feasible outcomes, missed feasible options and tail failures. Best known is not proof of a global optimum.</p></div></li></ol></div>
<div class="pf-result-preview"><span class="pf-planned-tag">Planned evidence format</span><h3>What a result must show.</h3><dl><div><dt>Design quality after checking</dt><dd>Not yet measured</dd></div><div><dt>Feasibility failures</dt><dd>Not yet measured</dd></div><div><dt>Total cost + elapsed time</dt><dd>Not yet measured</dd></div><div><dt>Reference + repeat uncertainty</dt><dd>Not yet measured</dd></div><div><dt>Network vs. centralized search</dt><dd>Not yet measured</dd></div></dl><p>No invented speedup. No mock leaderboard. Research, scientific qualification, security acceptance and production use remain separate states.</p></div></div>
<div class="pf-compare-footer"><p><strong>Two different proofs:</strong> better prediction against reality and cheaper verified decisions against the best workflow. A model must earn each claim separately.</p>${sourceLink("science")}</div>
</div></section>

<section class="pf-section pf-wrap" id="network" aria-labelledby="network-title"><div class="pf-section-heading"><p class="pf-eyebrow">05 / Capital, time and miner emissions</p><h2 id="network-title">Fund useful progress.<br>Not a permanent benchmark treadmill.</h2><p class="pf-intro">The network thesis is access to useful external research that a small internal team cannot supply as efficiently. More submissions are not proof. Better verified outcomes per dollar would be.</p></div>
<div class="pf-allocation-grid"><div class="pf-allocation-card"><p class="pf-eyebrow">Company capital + engineering time</p><h3>Build the exam and the customer wedge.</h3><p>Reference adequacy, scientific review, adapters, cost studies, instruments and customer discovery are investments. Scope and approve each program; measure custom effort and reuse rather than opening eight simultaneous builds.</p></div><div class="pf-allocation-card pf-allocation-accent"><p class="pf-eyebrow">Miner research + network rewards</p><h3>Earn a role in the research budget.</h3><p>Miners need complete public research provisions. Independent reconstruction and protected evaluation test useful advances. This page proposes research priorities; it does not set emissions, activate paying challenges or promise equal rewards across eight programs.</p></div></div>
<div class="pf-funding-heading"><h3>Proposed investment checkpoints</h3><p>Continue, narrow or pause on evidence. These are planning checkpoints, not new qualification rules or automatic spend approvals.</p></div>
<ol class="pf-funding"><li><span>01 / Reference</span><h4>Can we measure the job?</h4><p>Verify outputs, convergence, controls and failure handling; price the research kit and reference volume.</p></li><li><span>02 / Decision value</span><h4>Can the method beat a strong alternative?</h4><p>Run the cost study and fresh decision test. Complete the required challenge-specific training-budget study before limits or rewards are set.</p></li><li><span>03 / Physical + customer evidence</span><h4>Does it help in the field?</h4><p>Run approved prospective measurements, establish buyer pain and procurement, and deliver a rights-cleared finite pilot.</p></li><li><span>04 / Repeat use</span><h4>Does the work compound?</h4><p>Measure repeat purchases, delivery effort, lifecycle needs and external-research contribution before scaling.</p></li></ol>
<div class="pf-network-proof"><div><h3>The Bittensor test</h3><p>Compare network-led construction with competent centralized search under matched tasks, allowed data and full research budgets. Useful method diversity, faster verified improvement and lower discovery cost are the relevant signals. A centralized win is evidence we must act on, not hide.</p></div><div><h3>The value-capture boundary</h3><p>Company revenue, miner rewards and Alpha value are different quantities. Carbon's planned buyback-and-burn approach for useful subnet research still requires operating terms and legal/economic review. It creates no revenue share, token-holder entitlement or guaranteed return.</p></div></div>
<p class="pf-context-note">Battery remains the protocol-development lead. The commercial emphasis here does not bypass that lock, reference work, qualification or deployment authority. ${sourceLink("pipeline")} ${sourceLink("budgets")} ${sourceLink("canon")}</p>
</section>

<section class="pf-reality-section" id="reality" aria-labelledby="reality-title"><div class="pf-wrap"><div class="pf-section-heading"><p class="pf-eyebrow">06 / The capability we want to build</p><h2 id="reality-title">From learning a solver<br>to learning the physical system.</h2><p class="pf-intro">The ambitious end state: fast models that learn measured behavior, predict unseen interventions within a defined envelope and help choose the next useful experiment. Faster verified engineering decisions—not a universal replacement for physics or simulation.</p></div>
<div class="pf-reality-path"><div><span>01</span><h3>Start with known physics</h3><p>Qualified references and inexpensive models establish controls, causal inputs and a bounded job.</p></div><div><span>02</span><h3>Learn what the instrument reveals</h3><p>Use calibrated sensor records to estimate supported parameters or corrections. Sensor fit alone does not identify hidden physics.</p></div><div><span>03</span><h3>Predict before observing</h3><p>Commit forecasts before held-out experiments. Separate permitted online adaptation from a frozen forecast test.</p></div><div><span>04</span><h3>Use, monitor, re-evidence</h3><p>Abstain or fall back outside the supported envelope. Changes to model, hardware, data or conditions trigger new evidence.</p></div></div>
<div class="pf-reality-bottom"><div><p class="pf-eyebrow">First prospective pilot</p><h3>A heater. A plate.<br>A prediction made in advance.</h3><p>Burst-power thermal envelopes offer the first owned experimental path: known power input, measured temperature and an unseen power history. Price and approve the pilot, qualify the observations and compare against a calibrated RC model before expanding.</p></div><div class="pf-integrity"><h3>Harder to game, not declared ungameable.</h3><p>Sensor time, calibration, location, uncertainty, actuator history and raw-data custody must be recorded. Hold out whole experiments, devices or geometry families—not random neighboring samples. Independent future tests, not a producer's dashboard, establish success.</p><p>Use cheap research screens to prioritize work, independent numerical checks where appropriate and selected prospective experiments. No requirement to run four complete high-cost panels for every candidate; no screen replaces the complete evidence required by a scientific claim. Private sensor streams need approved rights and security arrangements.</p></div></div>
</div></section>

<section class="pf-section pf-wrap" id="market" aria-labelledby="market-title"><div class="pf-section-heading"><p class="pf-eyebrow">07 / Go to market</p><h2 id="market-title">Land with a specific question.<br>Expand when the evidence earns it.</h2><p class="pf-intro">Five customer clusters, eight bounded programs, one reusable discovery-and-evidence infrastructure. The portfolio is an account-entry hypothesis—not five validated markets or eight revenue lines.</p></div>
<div class="pf-market-table-wrap"><table class="pf-market-table"><caption>Proposed account-entry and expansion paths</caption><thead><tr><th scope="col">Customer cluster</th><th scope="col">First conversation</th><th scope="col">Potential repeat work</th></tr></thead><tbody><tr><th scope="row">AI hardware</th><td>Thermal design or transient-model evidence; optical coupling as a separate frontier program.</td><td>New packages, power histories, tolerance envelopes and optical stacks.</td></tr><tr><th scope="row">Battery engineering</th><td>Cell-specific charging/ageing decision evidence.</td><td>New cell batches, chemistry, operating conditions and justified assessment horizons.</td></tr><tr><th scope="row">Precision motion</th><td>Torque-curve or resonance-aware design evidence.</td><td>New actuator geometry, payloads, joints, supports and material measurements.</td></tr><tr><th scope="row">Industrial equipment</th><td>Bounded silencer feasibility and acoustic evidence.</td><td>Source bands, packaging, termination and separately scoped operating-flow checks.</td></tr><tr><th scope="row">Lab + process</th><td>Passive-mixing model or cartridge-design evidence.</td><td>New channel families, diffusivities, flow settings and measured transport.</td></tr></tbody></table></div>
<div class="pf-commercial-path"><span>Evidence Audit / feasibility</span><span aria-hidden="true">→</span><span>Sponsored discovery / development</span><span aria-hidden="true">→</span><span>Bounded qualification + integration</span><span aria-hidden="true">→</span><span>Lifecycle / repeat evidence</span></div>
<p class="pf-context-note">Every engagement needs a technical owner, budget owner, measurable current pain, feasible reference access, rights and an agreed treatment of negative results. Repeated expert work becomes software or API infrastructure only when demand and reuse justify it. ${sourceLink("canon")}</p>
<div class="pf-cta"><div><p class="pf-eyebrow">Build the next evidence-bearing decision.</p><h3>Have a physical problem<br>worth solving better?</h3><p>Tell us the decision, the current workflow and what better evidence would unlock.</p></div><a class="pf-button pf-button-dark" href="mailto:hello@carbonphysics.ai?subject=Carbon%20portfolio%20research">Discuss a research program ${arrow}</a></div>
</section>
</main>
<footer class="pf-footer"><div class="pf-wrap"><div class="pf-footer-top"><a class="pf-brand" href="https://carbonphysics.ai/" aria-label="Carbon home"><img src="../assets/brand-2.svg" alt="Carbon" width="172" height="40"></a><p>Discovery + Evidence Infrastructure for Physics AI</p><a href="#main">Back to top ↑</a></div><div class="pf-footer-meta"><p>Portfolio planning snapshot: ${reviewedDate}. Repository basis: <a href="https://github.com/carbonphysicsai/Carbon/tree/${evidenceRevision}" target="_blank" rel="noreferrer">${evidenceRevision.slice(0, 8)}</a>. Proposed programs and expansion opportunities; not scientific, security, commercial or production qualification. No prices, ROI, emissions allocation or returns are promised.</p><p>© 2026 Carbon Physics, Inc. All rights reserved.</p></div></div></footer>
</body>
</html>
`;
}
