"""Typed, deterministic, and non-disclosing A4 seeding boundaries."""

from .commitment import (
    create_fixture_official_exam_projection,
    create_official_exam_projection,
    serialize_exam_projection,
)
from .derive import (
    HKDF_SALT,
    derive_fixture_official_seed,
    derive_mock_seed,
    derive_official_seed,
    derive_qualification_seed,
)
from .model import (
    SEED_SCHEME_ID,
    ContextKind,
    DerivedSeed,
    EvaluationBinding,
    ExamCommitment,
    FixtureOfficialContext,
    FixtureOfficialEntropy,
    FixtureOfficialExamProjection,
    MockContext,
    MockEntropy,
    OfficialContext,
    OfficialEntropy,
    OfficialExamProjection,
    QualificationContext,
    QualificationEntropy,
    RoleKey,
    SeedDomain,
    SeedPin,
    SeedValidationError,
)
from .provider import (
    BeaconConflictError,
    BeaconProvider,
    DeterministicFixtureProvider,
    FixtureEntropyUnavailable,
    OfficialEntropyUnavailable,
    acquire_fixture_official_context,
    acquire_official_context,
)

__all__ = (
    "HKDF_SALT",
    "SEED_SCHEME_ID",
    "BeaconConflictError",
    "BeaconProvider",
    "ContextKind",
    "DerivedSeed",
    "DeterministicFixtureProvider",
    "EvaluationBinding",
    "ExamCommitment",
    "FixtureEntropyUnavailable",
    "FixtureOfficialContext",
    "FixtureOfficialEntropy",
    "FixtureOfficialExamProjection",
    "MockContext",
    "MockEntropy",
    "OfficialContext",
    "OfficialEntropy",
    "OfficialEntropyUnavailable",
    "OfficialExamProjection",
    "QualificationContext",
    "QualificationEntropy",
    "RoleKey",
    "SeedDomain",
    "SeedPin",
    "SeedValidationError",
    "acquire_fixture_official_context",
    "acquire_official_context",
    "create_fixture_official_exam_projection",
    "create_official_exam_projection",
    "derive_fixture_official_seed",
    "derive_mock_seed",
    "derive_official_seed",
    "derive_qualification_seed",
    "serialize_exam_projection",
)
